-- Protees Business Manager — Unit module restructure + Zakat tracking
--
-- Adds:
--   1. employees.employee_group ('regular' | 'unit') — Unit Employees'
--      salaries are excluded from Regular Payroll totals/reports and
--      counted toward Unit Payroll instead. Existing rows default to
--      'regular', so current behavior is unchanged for everyone.
--   2. expenses.expense_scope ('business' | 'unit') — Unit Expenses are
--      excluded from normal Business Expense totals and included in Unit
--      reports/dashboard calculations instead. Existing rows default to
--      'business' (unchanged behavior).
--   3. zakat_transactions — full history of Zakat distributions (recipient,
--      amount, date, notes), audited like every other business table.
--   4. zakat_settings — a single-row settings table holding the editable
--      monthly Zakat budget (defaults to Rs 100,000 per spec).
--
-- Does NOT touch: units, supervisors, unit_payments, advances (Give
-- Advance / Make Payment flow stays exactly as it is) or the Factory
-- module. No quantity/production tracking added anywhere.
--
-- Safe to re-run.

-- ---------------------------------------------------------------------------
-- 1. employees.employee_group
-- ---------------------------------------------------------------------------
alter table employees add column if not exists employee_group text not null default 'regular';
alter table employees drop constraint if exists employees_employee_group_check;
alter table employees add constraint employees_employee_group_check
  check (employee_group in ('regular', 'unit'));

-- ---------------------------------------------------------------------------
-- 2. expenses.expense_scope
-- ---------------------------------------------------------------------------
alter table expenses add column if not exists expense_scope text not null default 'business';
alter table expenses drop constraint if exists expenses_expense_scope_check;
alter table expenses add constraint expenses_expense_scope_check
  check (expense_scope in ('business', 'unit'));

-- ---------------------------------------------------------------------------
-- 3. zakat_transactions — audited like the other business tables
-- ---------------------------------------------------------------------------
create table if not exists zakat_transactions (
  id bigint generated by default as identity primary key,
  recipient_name text not null,
  amount numeric(12,2) not null,
  date date not null default current_date,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_zakat_transactions_date on zakat_transactions(date);

alter table zakat_transactions enable row level security;
drop policy if exists "authenticated app users only" on zakat_transactions;
create policy "authenticated app users only" on zakat_transactions for all using (is_app_user()) with check (is_app_user());

drop trigger if exists audit_zakat_transactions on zakat_transactions;
create trigger audit_zakat_transactions before insert or update or delete on zakat_transactions for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- 4. zakat_settings — single editable row holding the monthly budget
-- ---------------------------------------------------------------------------
create table if not exists zakat_settings (
  id int primary key default 1,
  monthly_budget numeric(12,2) not null default 100000,
  updated_at timestamptz not null default now(),
  constraint zakat_settings_singleton check (id = 1)
);
insert into zakat_settings (id, monthly_budget) values (1, 100000) on conflict (id) do nothing;

alter table zakat_settings enable row level security;
drop policy if exists "authenticated app users only" on zakat_settings;
create policy "authenticated app users only" on zakat_settings for all using (is_app_user()) with check (is_app_user());
