-- Grand Advances (Employee Loans) — long-term loans recovered through salary
-- deductions over multiple months, separate from normal advances.
--
-- Safe to re-run.

-- Grand Advances: the loan itself
create table if not exists grand_advances (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id) on delete cascade,
  original_amount numeric(12,2) not null check (original_amount > 0),
  outstanding_balance numeric(12,2) not null check (outstanding_balance >= 0),
  total_recovered numeric(12,2) not null default 0 check (total_recovered >= 0),
  monthly_recovery_amount numeric(12,2),
  status text not null default 'active' check (status in ('active', 'completed')),
  issue_date date not null,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id text,
  created_by_username text,
  updated_at timestamptz not null default now(),
  updated_by_user_id text,
  updated_by_username text,
  constraint grand_advances_balance_check check (
    total_recovered + outstanding_balance = original_amount
  ),
  constraint grand_advances_monthly_recovery_check check (
    monthly_recovery_amount is null or monthly_recovery_amount > 0
  )
);

create index if not exists idx_grand_advances_employee on grand_advances(employee_id);
create index if not exists idx_grand_advances_status on grand_advances(status);

-- Grand Advance Recoveries: each installment deducted from salary
create table if not exists grand_advance_recoveries (
  id bigint generated by default as identity primary key,
  grand_advance_id bigint not null references grand_advances(id) on delete cascade,
  recovery_amount numeric(12,2) not null check (recovery_amount > 0),
  salary_payment_id bigint references salary_payments(id) on delete set null,
  recovery_date date not null,
  created_at timestamptz not null default now(),
  created_by_user_id text,
  created_by_username text
);

create index if not exists idx_grand_advance_recoveries_grand_advance on grand_advance_recoveries(grand_advance_id);
create index if not exists idx_grand_advance_recoveries_salary on grand_advance_recoveries(salary_payment_id);
