-- Protees Business Manager — Khadim Hussain Account
-- Additive only: one new table (its own ledger of money given to Khadim
-- Hussain for unit material purchases, vs. bills he submits against it),
-- plus one category added to the existing expenses check constraint.
-- Nothing existing is dropped, renamed, or restructured.

create table if not exists khadim_transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('payment_given', 'bill_submitted')),
  date date not null default current_date,
  amount numeric(12,2) not null check (amount > 0),
  notes text,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_khadim_transactions_date on khadim_transactions(date);

alter table khadim_transactions enable row level security;
drop policy if exists "allow all" on khadim_transactions;
create policy "allow all" on khadim_transactions for all using (true) with check (true);

-- ---------------------------------------------------------------------------
-- Expense module integration — "Khadim Hussain" becomes a selectable
-- Unit Expense category alongside the existing ones.
-- ---------------------------------------------------------------------------
alter table expenses drop constraint if exists expenses_category_check;
alter table expenses add constraint expenses_category_check
  check (category in ('Thread', 'Fabric', 'Packing', 'Transport', 'Printing', 'Khadim Hussain', 'Other Expenses'));
