-- Protees Business Manager — Shopify multi-store support.
--
-- shopify_stores holds ONLY non-secret config (domain, display name,
-- live connection status) — Admin API access tokens are never stored
-- here or anywhere in the database. They live exclusively in
-- server-only Vercel environment variables (SHOPIFY_<STORE_KEY>_TOKEN),
-- read only by the /api/shopify-sync serverless function, which writes
-- to shopify_orders using the Supabase service-role key (bypasses RLS).
-- The client only ever reads shopify_stores for status/labels.
--
-- shopify_orders gains store_key (which store an order came from) plus
-- customer_phone/customer_city, both requested for the collections
-- table.
--
-- Safe to re-run.

create table if not exists shopify_stores (
  id bigint generated by default as identity primary key,
  store_key text not null unique,
  display_name text not null,
  store_domain text,
  is_connected boolean not null default false,
  last_synced_at timestamptz,
  last_sync_error text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);

insert into shopify_stores (store_key, display_name) values
  ('protees', 'Protees'),
  ('little_peanuts', 'Little Peanuts')
on conflict (store_key) do nothing;

alter table shopify_orders add column if not exists store_key text references shopify_stores(store_key);
alter table shopify_orders add column if not exists customer_phone text;
alter table shopify_orders add column if not exists customer_city text;

create index if not exists idx_shopify_orders_store on shopify_orders(store_key);

drop trigger if exists audit_shopify_stores on shopify_stores;
create trigger audit_shopify_stores before insert or update or delete on shopify_stores for each row execute function stamp_and_log_audit();

alter table shopify_stores enable row level security;

drop policy if exists "authenticated app users only" on shopify_stores;
create policy "authenticated app users only" on shopify_stores for all using (is_app_user()) with check (is_app_user());
