-- Protees Business Manager — Collections module: Shopify orders, Courier
-- Accounts Receivable, Bank Accounts, and Office Cash Management.
--
-- New tables, all additive and RLS-protected with the existing
-- is_app_user() helper (same pattern as every other business table) —
-- except shopify_orders, which is read-only from the client (only a
-- future server-side sync, using the service-role key, ever writes to
-- it — the app itself never inserts/updates/deletes there).
--
-- Courier Accounts is a real Accounts Receivable model:
--   Pending Balance (per courier) = Total Expected Collections
--                                 - Total Payments Received
-- "Expected Collection" is recorded manually when a COD shipment goes
-- out (courier_expected_collections); "Payments Received" is recorded
-- when the courier actually remits money (courier_payments). Recording
-- a payment does not touch the expected side — the balance simply falls
-- out of the subtraction, so it can never drift.
--
-- Bank balances and the Office Cash balance are both derived the same
-- way, from append-only ledgers (bank_transactions, cash_transactions)
-- rather than a stored running total — the same "ledger, not balance
-- column" convention already used by advance_deductions elsewhere in
-- this schema.
--
-- Safe to re-run.

-- ---------------------------------------------------------------------------
-- Couriers
-- ---------------------------------------------------------------------------
create table if not exists couriers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);

-- ---------------------------------------------------------------------------
-- Courier expected collections — the "receivable" side. Recorded when a
-- COD shipment is handed to a courier.
-- ---------------------------------------------------------------------------
create table if not exists courier_expected_collections (
  id bigint generated by default as identity primary key,
  courier_id bigint not null references couriers(id),
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  order_reference text,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_courier_expected_courier on courier_expected_collections(courier_id);

-- ---------------------------------------------------------------------------
-- Bank accounts — seeded with Meezan Bank and Bank Alfalah, extensible.
-- Note: "Cash" is NOT a bank account — it's tracked by cash_transactions.
-- ---------------------------------------------------------------------------
create table if not exists bank_accounts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
insert into bank_accounts (name) values ('Meezan Bank'), ('Bank Alfalah') on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Courier payments — the "received" side. Recording one here
-- automatically inserts a matching bank_transactions credit (if bank
-- transfer) or cash_transactions cash_in (if cash) — done atomically by
-- the app in one write, not by a database trigger, so the app can show
-- the exact combined result immediately.
-- ---------------------------------------------------------------------------
create table if not exists courier_payments (
  id bigint generated by default as identity primary key,
  courier_id bigint not null references couriers(id),
  amount numeric(12,2) not null check (amount > 0),
  payment_date date not null default current_date,
  payment_type text not null check (payment_type in ('cash', 'bank_transfer')),
  bank_account_id bigint references bank_accounts(id),
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz,
  constraint courier_payments_bank_required check (
    (payment_type = 'bank_transfer' and bank_account_id is not null) or
    (payment_type = 'cash' and bank_account_id is null)
  )
);
create index if not exists idx_courier_payments_courier on courier_payments(courier_id);

-- ---------------------------------------------------------------------------
-- Bank ledger — append-only. A bank's balance = sum(credit) - sum(debit).
-- ---------------------------------------------------------------------------
create table if not exists bank_transactions (
  id bigint generated by default as identity primary key,
  bank_account_id bigint not null references bank_accounts(id),
  type text not null check (type in ('credit', 'debit')),
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  reference_type text check (reference_type in ('courier_payment', 'cash_withdrawal', 'manual')),
  reference_id bigint,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text
);
create index if not exists idx_bank_transactions_bank on bank_transactions(bank_account_id);

-- ---------------------------------------------------------------------------
-- Cash ledger — append-only. Office Cash balance = opening_balance (see
-- cash_settings) + sum(cash_in) - sum(cash_out).
-- ---------------------------------------------------------------------------
create table if not exists cash_transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('cash_in', 'cash_out')),
  category text not null,
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  reference_type text check (reference_type in ('courier_payment', 'bank_withdrawal', 'expense', 'other')),
  reference_id bigint,
  bank_account_id bigint references bank_accounts(id),
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text
);
create index if not exists idx_cash_transactions_date on cash_transactions(date);

-- ---------------------------------------------------------------------------
-- Cash opening balance — singleton row, same pattern as zakat_settings.
-- ---------------------------------------------------------------------------
create table if not exists cash_settings (
  id int primary key default 1,
  opening_balance numeric(12,2) not null default 0,
  opening_date date not null default current_date,
  updated_at timestamptz not null default now(),
  constraint cash_settings_singleton check (id = 1)
);
insert into cash_settings (id) values (1) on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Shopify orders — populated ONLY by a future server-side sync (Vercel
-- function using the Supabase service-role key, which bypasses RLS). The
-- app itself never writes here — the RLS policy below only grants SELECT.
-- ---------------------------------------------------------------------------
create table if not exists shopify_orders (
  id bigint generated by default as identity primary key,
  shopify_order_id text not null unique,
  shopify_transaction_id text,
  order_number text not null,
  order_date timestamptz not null,
  customer_name text,
  total_amount numeric(12,2) not null,
  payment_method text,
  financial_status text not null,
  imported_at timestamptz not null default now()
);
create index if not exists idx_shopify_orders_date on shopify_orders(order_date);

-- Non-secret settings only — the Admin API token is a server-only env
-- var and is never stored in the database.
create table if not exists shopify_settings (
  id int primary key default 1,
  store_domain text,
  last_synced_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint shopify_settings_singleton check (id = 1)
);
insert into shopify_settings (id) values (1) on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Audit trail — reuse the existing stamp_and_log_audit() trigger (defined
-- in migration_007) on every editable table. Ledgers (bank_transactions,
-- cash_transactions) are append-only — created_by only, no update path in
-- the app, same convention as advance_deductions.
-- ---------------------------------------------------------------------------
drop trigger if exists audit_couriers on couriers;
create trigger audit_couriers before insert or update or delete on couriers for each row execute function stamp_and_log_audit();

drop trigger if exists audit_courier_expected_collections on courier_expected_collections;
create trigger audit_courier_expected_collections before insert or update or delete on courier_expected_collections for each row execute function stamp_and_log_audit();

drop trigger if exists audit_bank_accounts on bank_accounts;
create trigger audit_bank_accounts before insert or update or delete on bank_accounts for each row execute function stamp_and_log_audit();

drop trigger if exists audit_courier_payments on courier_payments;
create trigger audit_courier_payments before insert or update or delete on courier_payments for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table couriers enable row level security;
alter table courier_expected_collections enable row level security;
alter table bank_accounts enable row level security;
alter table courier_payments enable row level security;
alter table bank_transactions enable row level security;
alter table cash_transactions enable row level security;
alter table cash_settings enable row level security;
alter table shopify_orders enable row level security;
alter table shopify_settings enable row level security;

drop policy if exists "authenticated app users only" on couriers;
create policy "authenticated app users only" on couriers for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on courier_expected_collections;
create policy "authenticated app users only" on courier_expected_collections for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on bank_accounts;
create policy "authenticated app users only" on bank_accounts for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on courier_payments;
create policy "authenticated app users only" on courier_payments for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on bank_transactions;
create policy "authenticated app users only" on bank_transactions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on cash_transactions;
create policy "authenticated app users only" on cash_transactions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on cash_settings;
create policy "authenticated app users only" on cash_settings for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on shopify_settings;
create policy "authenticated app users only" on shopify_settings for all using (is_app_user()) with check (is_app_user());

-- shopify_orders: read-only from the client — only SELECT is granted.
-- The future server-side sync writes with the service-role key, which
-- bypasses RLS entirely, so no INSERT/UPDATE policy is needed for it.
drop policy if exists "app users read only" on shopify_orders;
create policy "app users read only" on shopify_orders for select using (is_app_user());
