-- Protees Business Manager — Attendance Module (ZKTeco K40 integration).
--
-- ARCHITECTURE NOTE: this app runs on Vercel (the cloud), not on the office
-- LAN — it has no network path to dial a device at a private IP like
-- 192.168.x.x. Attendance rows land here (in `attendance`) either via
-- manual entry in the app, or via the separate zkteco-bridge/ script
-- (a small Node program that runs on a PC physically on the office LAN,
-- talks to the K40 over TCP, and pushes rows into this table using the
-- Supabase REST API). The app itself never dials the machine directly —
-- `zkteco_devices.ip_address` is configuration the bridge script reads,
-- not something the web app connects to.
--
-- Safe to re-run.

-- ---------------------------------------------------------------------------
-- Employee profile additions
-- ---------------------------------------------------------------------------
alter table employees add column if not exists employee_code text;
alter table employees add column if not exists department text;
alter table employees add column if not exists salary_date int;
alter table employees drop constraint if exists employees_salary_date_check;
alter table employees add constraint employees_salary_date_check check (salary_date is null or (salary_date between 1 and 31));
-- The K40's own internal enrollment id for this person — how machine punch
-- logs (which only carry a numeric user id, no name) get matched back to
-- an employees row. Unique so two employees can't accidentally map to the
-- same fingerprint enrollment.
alter table employees add column if not exists machine_user_id text;
create unique index if not exists idx_employees_machine_user_id on employees(machine_user_id) where machine_user_id is not null;

-- ---------------------------------------------------------------------------
-- Attendance — one row per employee per calendar date. Check-in/out are the
-- first/last punch of the day; a machine sync upserts onto the same row as
-- more punches come in rather than creating duplicates.
-- ---------------------------------------------------------------------------
create table if not exists attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id) on delete cascade,
  date date not null,
  check_in timestamptz,
  check_out timestamptz,
  status text not null check (status in ('present', 'absent', 'late', 'half_day', 'paid_leave', 'unpaid_leave', 'government_holiday')),
  leave_type text check (leave_type in ('sick', 'casual', 'other')),
  working_hours numeric(6,2),
  shortage_hours numeric(6,2),
  late_minutes int,
  early_leave_minutes int,
  overtime_hours numeric(6,2),
  -- Source distinguishes a machine-synced punch from a manual correction —
  -- the Attendance page needs this so admin edits are visibly distinct
  -- from what the K40 actually recorded.
  source text not null default 'manual' check (source in ('machine', 'manual')),
  -- The K40 log's own identifier (or a device+timestamp composite the
  -- bridge script derives) — how re-running a sync avoids inserting the
  -- same punch twice. Null for manual entries.
  machine_log_id text,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz,
  unique (employee_id, date)
);
create index if not exists idx_attendance_date on attendance(date);
create index if not exists idx_attendance_employee on attendance(employee_id);

drop trigger if exists audit_attendance on attendance;
create trigger audit_attendance before insert or update or delete on attendance for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- Government Holidays — a holiday date auto-marks that day as a paid,
-- no-deduction status for everyone (applied in the app, not by a trigger,
-- so a manual override on a specific employee's row is still possible).
-- ---------------------------------------------------------------------------
create table if not exists government_holidays (
  id bigint generated by default as identity primary key,
  date date not null unique,
  name text not null,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);

drop trigger if exists audit_government_holidays on government_holidays;
create trigger audit_government_holidays before insert or update or delete on government_holidays for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- Attendance Settings — singleton, same pattern as cash_settings/
-- zakat_settings. Standard hours/break/grace used to derive shortage,
-- late, and overtime for every attendance row.
-- ---------------------------------------------------------------------------
create table if not exists attendance_settings (
  id int primary key default 1,
  standard_working_hours numeric(4,2) not null default 8,
  break_minutes int not null default 60,
  standard_start_time time not null default '09:00',
  late_grace_minutes int not null default 15,
  -- Left at 0 (no penalty) until admin explicitly sets one — being marked
  -- "Late" alone should never silently cost someone money.
  late_penalty_per_instance numeric(12,2) not null default 0,
  updated_at timestamptz not null default now(),
  constraint attendance_settings_singleton check (id = 1)
);
insert into attendance_settings (id) values (1) on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- ZKTeco devices — config the bridge script reads (see architecture note
-- above). last_synced_at/last_sync_error let the Attendance Settings page
-- show sync health even though the web app never talks to the device.
-- ---------------------------------------------------------------------------
create table if not exists zkteco_devices (
  id bigint generated by default as identity primary key,
  name text not null,
  ip_address text not null,
  port int not null default 4370,
  is_active boolean not null default true,
  last_synced_at timestamptz,
  last_sync_error text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);

drop trigger if exists audit_zkteco_devices on zkteco_devices;
create trigger audit_zkteco_devices before insert or update or delete on zkteco_devices for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- Payroll integration — attendance-derived figures snapshotted onto the
-- salary payment at the moment it's recorded (same "snapshot the inputs"
-- pattern as pieces_completed/rate_per_piece).
--
-- salary_payments.overtime_amount ALREADY EXISTS (not null default 0) —
-- it's reused as-is: the app computes it from overtime_hours × rate and
-- writes it in only when overtime_included is checked, exactly like the
-- existing manual overtime entry already works. overtime_hours here is
-- just the attendance-derived figure available to include, kept separate
-- so the UI can still show "X hours available" even when unchecked.
-- ---------------------------------------------------------------------------
alter table salary_payments add column if not exists overtime_hours numeric(6,2);
alter table salary_payments add column if not exists overtime_included boolean not null default false;
alter table salary_payments add column if not exists absent_deduction numeric(12,2) not null default 0;
alter table salary_payments add column if not exists late_deduction numeric(12,2) not null default 0;
alter table salary_payments add column if not exists leave_deduction numeric(12,2) not null default 0;

-- ---------------------------------------------------------------------------
-- Master Data: Department is a free, admin-managed list like everything
-- else in Settings → Master Data — reuses migration_016's engine instead
-- of a new bespoke table.
-- ---------------------------------------------------------------------------
insert into master_data_types (key, label, sort_order) values
  ('department', 'Departments', 5)
on conflict (key) do nothing;

insert into master_data_items (type_key, name, sort_order) values
  ('department', 'Cutting', 10),
  ('department', 'Stitching', 20),
  ('department', 'Printing', 30),
  ('department', 'DTF', 40),
  ('department', 'Quality', 50),
  ('department', 'Store', 60),
  ('department', 'Management', 70)
on conflict (type_key, name) do nothing;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table attendance enable row level security;
alter table government_holidays enable row level security;
alter table attendance_settings enable row level security;
alter table zkteco_devices enable row level security;

drop policy if exists "authenticated app users only" on attendance;
create policy "authenticated app users only" on attendance for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on government_holidays;
create policy "authenticated app users only" on government_holidays for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on attendance_settings;
create policy "authenticated app users only" on attendance_settings for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on zkteco_devices;
create policy "authenticated app users only" on zkteco_devices for all using (is_app_user()) with check (is_app_user());
