-- Protees Business Manager — dynamic Unit Expense categories
-- Moves categories from a hardcoded check constraint to a real table so new
-- categories can be added from the app with zero code changes. Additive
-- only: existing expenses and their category values are untouched — the
-- check constraint is simply removed (categories become free text backed
-- by this new table instead of a fixed list).

create table if not exists expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

-- Seed with every category that already existed, plus the newly requested
-- ones. "on conflict do nothing" makes this safe to re-run.
insert into expense_categories (name) values
  ('Thread'),
  ('Fabric'),
  ('Packing'),
  ('Transport'),
  ('Printing'),
  ('Khadim Hussain'),
  ('Food Grocery'),
  ('Food Vegetable'),
  ('Rotiyan'),
  ('Gas'),
  ('Diesel'),
  ('Transportation'),
  ('Other Expenses')
on conflict (name) do nothing;

alter table expense_categories enable row level security;
drop policy if exists "allow all" on expense_categories;
create policy "allow all" on expense_categories for all using (true) with check (true);

-- Categories are now database-driven — drop the fixed check constraint so
-- new categories don't require a schema change to use.
alter table expenses drop constraint if exists expenses_category_check;
