-- Protees Business Manager — main-app authentication + full audit trail
--
-- Adds:
--   1. app_users: maps a fixed username (aqeel/arslan) to a Supabase Auth
--      account, so the main app can offer username-based login while
--      Supabase Auth itself still authenticates by email under the hood.
--   2. audit_log: an append-only record of every create/update/delete
--      across the business tables, including a full snapshot of deleted
--      rows (which otherwise vanish with no trace).
--   3. created_by_user_id / created_by_username / updated_by_user_id /
--      updated_by_username / updated_at columns on every business table,
--      auto-stamped by a trigger — no frontend code has to set these.
--   4. RLS on the business tables tightened from "allow all" to
--      "must be a row in app_users" — closing the anon-key-can-write-
--      anything gap now that the app has real logins.
--
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / OR
-- REPLACE / DROP POLICY IF EXISTS). Existing rows are untouched — the new
-- columns come in NULL for pre-existing records, which is expected (see
-- migration notes shared with the user).
--
-- Does NOT touch: the Factory module (profiles, colors, products,
-- product_sizes, product_colors, product_operations,
-- product_operation_rates, production_plans, production_plan_sizes) or
-- its RLS/auth — that stays exactly as it is.

-- ---------------------------------------------------------------------------
-- 1. app_users
-- ---------------------------------------------------------------------------
create table if not exists app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

-- SECURITY DEFINER so it bypasses RLS on app_users internally — used by
-- every policy below instead of a raw "select id from app_users" subquery.
-- That raw form would re-trigger app_users' own RLS policy every time it's
-- evaluated (including from app_users' own policy), causing Postgres error
-- 42P17 "infinite recursion detected in policy for relation app_users".
create or replace function public.is_app_user()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (select 1 from app_users where id = auth.uid());
$$;

alter table app_users enable row level security;
drop policy if exists "allowed users read directory" on app_users;
create policy "allowed users read directory" on app_users
  for select using (is_app_user());

-- Resolves username -> email for the login screen, callable *before* the
-- user is authenticated (grant to anon). Returns nothing for an unknown
-- username. security definer so it can read app_users regardless of the
-- caller's own row-level access (there isn't one yet, pre-login).
create or replace function public.resolve_login_email(p_username text)
returns text
language sql
security definer
stable
set search_path = public
as $$
  select email from app_users where username = lower(trim(p_username));
$$;
grant execute on function public.resolve_login_email(text) to anon, authenticated;

-- Seed the two allowed users. Run this block only after both Supabase Auth
-- accounts already exist (arslanjamil6@gmail.com and mianaqeel125@gmail.com
-- — both confirmed to exist already).
insert into app_users (id, username, display_name, email)
select id, 'arslan', 'Arslan', email from auth.users where email = 'arslanjamil6@gmail.com'
on conflict (id) do update set username = excluded.username, display_name = excluded.display_name, email = excluded.email;

insert into app_users (id, username, display_name, email)
select id, 'aqeel', 'Aqeel', email from auth.users where email = 'mianaqeel125@gmail.com'
on conflict (id) do update set username = excluded.username, display_name = excluded.display_name, email = excluded.email;

-- Helper used by the audit trigger to resolve "who is doing this write".
create or replace function public.current_app_username()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select username from app_users where id = auth.uid();
$$;

-- ---------------------------------------------------------------------------
-- 2. audit_log — append-only, written only by the trigger below (security
--    definer), never directly by the app.
-- ---------------------------------------------------------------------------
create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  action text not null check (action in ('create', 'update', 'delete')),
  performed_by uuid,
  performed_by_username text,
  performed_at timestamptz not null default now(),
  old_data jsonb,
  new_data jsonb
);
create index if not exists idx_audit_log_table_record on audit_log(table_name, record_id);
create index if not exists idx_audit_log_performed_at on audit_log(performed_at desc);

alter table audit_log enable row level security;
drop policy if exists "allowed users read audit log" on audit_log;
create policy "allowed users read audit log" on audit_log
  for select using (is_app_user());

-- ---------------------------------------------------------------------------
-- 3. Reusable trigger: stamps created_by_*/updated_by_* on the row AND
--    writes an audit_log entry, for insert/update/delete alike.
-- ---------------------------------------------------------------------------
create or replace function public.stamp_and_log_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  uname text := current_app_username();
begin
  if tg_op = 'INSERT' then
    new.created_by_user_id := auth.uid();
    new.created_by_username := uname;
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, new_data)
      values (tg_table_name, new.id::text, 'create', auth.uid(), uname, to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_by_user_id := auth.uid();
    new.updated_by_username := uname;
    new.updated_at := now();
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, old_data, new_data)
      values (tg_table_name, new.id::text, 'update', auth.uid(), uname, to_jsonb(old), to_jsonb(new));
    return new;
  elsif tg_op = 'DELETE' then
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, old_data)
      values (tg_table_name, old.id::text, 'delete', auth.uid(), uname, to_jsonb(old));
    return old;
  end if;
  return null;
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. Per-table: add attribution columns + attach the trigger.
--    Covers every business table that can be created/edited/deleted.
--    Written as flat, explicit statements (not a PL/pgSQL loop) so that if
--    any single line fails, Supabase's SQL editor points at that exact
--    line instead of an opaque "error in PL/pgSQL function" — and so nothing
--    hides inside a DO block that could obscure a failure.
-- ---------------------------------------------------------------------------
alter table employees add column if not exists created_by_user_id uuid;
alter table employees add column if not exists created_by_username text;
alter table employees add column if not exists updated_by_user_id uuid;
alter table employees add column if not exists updated_by_username text;
alter table employees add column if not exists updated_at timestamptz;
drop trigger if exists audit_employees on employees;
create trigger audit_employees before insert or update or delete on employees for each row execute function stamp_and_log_audit();

alter table supervisors add column if not exists created_by_user_id uuid;
alter table supervisors add column if not exists created_by_username text;
alter table supervisors add column if not exists updated_by_user_id uuid;
alter table supervisors add column if not exists updated_by_username text;
alter table supervisors add column if not exists updated_at timestamptz;
drop trigger if exists audit_supervisors on supervisors;
create trigger audit_supervisors before insert or update or delete on supervisors for each row execute function stamp_and_log_audit();

alter table advances add column if not exists created_by_user_id uuid;
alter table advances add column if not exists created_by_username text;
alter table advances add column if not exists updated_by_user_id uuid;
alter table advances add column if not exists updated_by_username text;
alter table advances add column if not exists updated_at timestamptz;
drop trigger if exists audit_advances on advances;
create trigger audit_advances before insert or update or delete on advances for each row execute function stamp_and_log_audit();

alter table salary_payments add column if not exists created_by_user_id uuid;
alter table salary_payments add column if not exists created_by_username text;
alter table salary_payments add column if not exists updated_by_user_id uuid;
alter table salary_payments add column if not exists updated_by_username text;
alter table salary_payments add column if not exists updated_at timestamptz;
drop trigger if exists audit_salary_payments on salary_payments;
create trigger audit_salary_payments before insert or update or delete on salary_payments for each row execute function stamp_and_log_audit();

alter table unit_payments add column if not exists created_by_user_id uuid;
alter table unit_payments add column if not exists created_by_username text;
alter table unit_payments add column if not exists updated_by_user_id uuid;
alter table unit_payments add column if not exists updated_by_username text;
alter table unit_payments add column if not exists updated_at timestamptz;
drop trigger if exists audit_unit_payments on unit_payments;
create trigger audit_unit_payments before insert or update or delete on unit_payments for each row execute function stamp_and_log_audit();

alter table advance_deductions add column if not exists created_by_user_id uuid;
alter table advance_deductions add column if not exists created_by_username text;
alter table advance_deductions add column if not exists updated_by_user_id uuid;
alter table advance_deductions add column if not exists updated_by_username text;
alter table advance_deductions add column if not exists updated_at timestamptz;
drop trigger if exists audit_advance_deductions on advance_deductions;
create trigger audit_advance_deductions before insert or update or delete on advance_deductions for each row execute function stamp_and_log_audit();

alter table expenses add column if not exists created_by_user_id uuid;
alter table expenses add column if not exists created_by_username text;
alter table expenses add column if not exists updated_by_user_id uuid;
alter table expenses add column if not exists updated_by_username text;
alter table expenses add column if not exists updated_at timestamptz;
drop trigger if exists audit_expenses on expenses;
create trigger audit_expenses before insert or update or delete on expenses for each row execute function stamp_and_log_audit();

alter table expense_categories add column if not exists created_by_user_id uuid;
alter table expense_categories add column if not exists created_by_username text;
alter table expense_categories add column if not exists updated_by_user_id uuid;
alter table expense_categories add column if not exists updated_by_username text;
alter table expense_categories add column if not exists updated_at timestamptz;
drop trigger if exists audit_expense_categories on expense_categories;
create trigger audit_expense_categories before insert or update or delete on expense_categories for each row execute function stamp_and_log_audit();

alter table khadim_transactions add column if not exists created_by_user_id uuid;
alter table khadim_transactions add column if not exists created_by_username text;
alter table khadim_transactions add column if not exists updated_by_user_id uuid;
alter table khadim_transactions add column if not exists updated_by_username text;
alter table khadim_transactions add column if not exists updated_at timestamptz;
drop trigger if exists audit_khadim_transactions on khadim_transactions;
create trigger audit_khadim_transactions before insert or update or delete on khadim_transactions for each row execute function stamp_and_log_audit();

alter table units add column if not exists created_by_user_id uuid;
alter table units add column if not exists created_by_username text;
alter table units add column if not exists updated_by_user_id uuid;
alter table units add column if not exists updated_by_username text;
alter table units add column if not exists updated_at timestamptz;
drop trigger if exists audit_units on units;
create trigger audit_units before insert or update or delete on units for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- 5. RLS tightening — replace "allow all" with "must be an allowed user".
--    Untouched: profiles/colors/products/... (Factory module) and
--    app_users/audit_log (already policed above). Same flat-statement
--    reasoning as section 4.
-- ---------------------------------------------------------------------------
drop policy if exists "allow all" on employees;
create policy "authenticated app users only" on employees for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on supervisors;
create policy "authenticated app users only" on supervisors for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on advances;
create policy "authenticated app users only" on advances for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on expenses;
create policy "authenticated app users only" on expenses for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on salary_payments;
create policy "authenticated app users only" on salary_payments for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on unit_payments;
create policy "authenticated app users only" on unit_payments for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on advance_deductions;
create policy "authenticated app users only" on advance_deductions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on units;
create policy "authenticated app users only" on units for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on khadim_transactions;
create policy "authenticated app users only" on khadim_transactions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on expense_categories;
create policy "authenticated app users only" on expense_categories for all using (is_app_user()) with check (is_app_user());
