-- Protees Business Manager — Collections v2: single-module redesign.
--
-- Replaces the "expected vs received" Accounts Receivable model
-- (courier_expected_collections + courier_payments) with a simpler
-- one-step model: a courier is configured ONCE with how it pays
-- (cash, or bank transfer into a specific account), and every
-- "Add Collection" entry for that courier automatically posts to the
-- right ledger — no per-entry bank/payment-type selection.
--
-- courier_expected_collections and courier_payments are NOT dropped
-- here (in case either already holds real data) — they're simply no
-- longer written to by the app. Safe to drop manually later once
-- confirmed empty.
--
-- Safe to re-run.

-- ---------------------------------------------------------------------------
-- Couriers: payment method is now a one-time configuration, not a
-- per-collection choice.
-- ---------------------------------------------------------------------------
alter table couriers add column if not exists payment_method text not null default 'cash' check (payment_method in ('cash', 'bank_transfer'));
alter table couriers add column if not exists bank_account_id bigint references bank_accounts(id);

alter table couriers drop constraint if exists couriers_bank_required;
alter table couriers add constraint couriers_bank_required check (
  (payment_method = 'bank_transfer' and bank_account_id is not null) or
  (payment_method = 'cash' and bank_account_id is null)
);

-- ---------------------------------------------------------------------------
-- Courier collections — one entry per actual collection. Recording one
-- automatically posts a matching bank_transactions credit (if the
-- courier is configured for bank transfer) or cash_transactions cash_in
-- (if cash) — done atomically by the app in one write.
-- ---------------------------------------------------------------------------
create table if not exists courier_collections (
  id bigint generated by default as identity primary key,
  courier_id bigint not null references couriers(id),
  invoice_number text,
  invoice_date date not null default current_date,
  amount numeric(12,2) not null check (amount > 0),
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_courier_collections_courier on courier_collections(courier_id);

-- ---------------------------------------------------------------------------
-- Cash transfers — moving money from a bank account into Office Cash
-- (e.g. withdrawing collected funds to pay cash expenses). Debits the
-- bank, credits cash, atomically.
-- ---------------------------------------------------------------------------
create table if not exists cash_transfers (
  id bigint generated by default as identity primary key,
  bank_account_id bigint not null references bank_accounts(id),
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_cash_transfers_bank on cash_transfers(bank_account_id);

-- ---------------------------------------------------------------------------
-- Widen ledger reference_type check constraints for the new reference
-- kinds. Old values are kept for backward compatibility with any
-- existing rows.
-- ---------------------------------------------------------------------------
alter table bank_transactions drop constraint if exists bank_transactions_reference_type_check;
alter table bank_transactions add constraint bank_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'cash_withdrawal', 'manual', 'courier_collection', 'cash_transfer'));

alter table cash_transactions drop constraint if exists cash_transactions_reference_type_check;
alter table cash_transactions add constraint cash_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'bank_withdrawal', 'expense', 'other', 'courier_collection', 'cash_transfer'));

-- ---------------------------------------------------------------------------
-- Audit trail + RLS
-- ---------------------------------------------------------------------------
drop trigger if exists audit_courier_collections on courier_collections;
create trigger audit_courier_collections before insert or update or delete on courier_collections for each row execute function stamp_and_log_audit();

drop trigger if exists audit_cash_transfers on cash_transfers;
create trigger audit_cash_transfers before insert or update or delete on cash_transfers for each row execute function stamp_and_log_audit();

alter table courier_collections enable row level security;
alter table cash_transfers enable row level security;

drop policy if exists "authenticated app users only" on courier_collections;
create policy "authenticated app users only" on courier_collections for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on cash_transfers;
create policy "authenticated app users only" on cash_transfers for all using (is_app_user()) with check (is_app_user());
