-- Protees Business Manager — Master Data Engine.
--
-- A generic, admin-configurable dropdown system. Every "type" (Creditor
-- Categories, Payment Methods, Colors, Units, ...) is a fixed slot defined
-- here in code — but the VALUES inside each slot are fully dynamic: admin
-- can create/rename/archive them from the Settings screen with no
-- developer/deploy step required. This is the same trade-off every real
-- ERP makes (Odoo, Shopify, etc. have fixed models with dynamic records) —
-- a fully meta-meta system (dynamic types too) would add complexity with
-- no real benefit, since the UI needs a label/grouping per type anyway.
--
-- Safe to re-run.

create table if not exists master_data_types (
  key text primary key,
  label text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists master_data_items (
  id bigint generated by default as identity primary key,
  type_key text not null references master_data_types(key) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz,
  unique (type_key, name)
);
create index if not exists idx_master_data_items_type on master_data_items(type_key);

drop trigger if exists audit_master_data_items on master_data_items;
create trigger audit_master_data_items before insert or update or delete on master_data_items for each row execute function stamp_and_log_audit();

insert into master_data_types (key, label, sort_order) values
  ('creditor_category', 'Creditor Categories', 10),
  ('supplier_category', 'Supplier Categories', 20),
  ('material_category', 'Material Categories', 30),
  ('fabric_type', 'Fabric Types', 40),
  ('fabric_gsm', 'Fabric GSM Types', 50),
  ('color', 'Colors', 60),
  ('unit', 'Units', 70),
  ('payment_method', 'Payment Methods', 80),
  ('vendor_type', 'Vendor Types', 90),
  ('service_type', 'Service Types', 100),
  ('tag', 'Tags', 110),
  ('label', 'Labels', 120),
  ('status', 'Statuses', 130)
on conflict (key) do nothing;

-- Seed data — a starting point, not a limit. Admin can rename, archive, or
-- add unlimited values to any of these from Settings → Master Data.
insert into master_data_items (type_key, name, sort_order) values
  ('creditor_category', 'Fabric Supplier', 10),
  ('creditor_category', 'Trader', 20),
  ('creditor_category', 'Printing Vendor', 30),
  ('creditor_category', 'Machinery Vendor', 40),
  ('creditor_category', 'Service Provider', 50),
  ('creditor_category', 'Local Market Supplier', 60),
  ('creditor_category', 'Import Supplier', 70),
  ('payment_method', 'Cash', 10),
  ('payment_method', 'Bank Transfer', 20),
  ('payment_method', 'Cheque', 30),
  ('unit', 'KG', 10),
  ('unit', 'Meter', 20),
  ('unit', 'Roll', 30),
  ('unit', 'Piece', 40),
  ('unit', 'Bundle', 50),
  ('unit', 'Box', 60),
  ('fabric_type', 'Fleece', 10),
  ('fabric_type', 'Jersey', 20),
  ('fabric_type', 'Interlock', 30),
  ('fabric_type', 'Rib', 40),
  ('color', 'Black', 10),
  ('color', 'White', 20),
  ('color', 'Navy', 30)
on conflict (type_key, name) do nothing;

alter table master_data_types enable row level security;
alter table master_data_items enable row level security;

drop policy if exists "authenticated app users only" on master_data_types;
create policy "authenticated app users only" on master_data_types for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on master_data_items;
create policy "authenticated app users only" on master_data_items for all using (is_app_user()) with check (is_app_user());
