-- Protees Business Manager — Salary Increment System + Payment Ledger fix.
--
-- 1. Salary Increments: a full audit trail of raises. employees.salary
--    stays the CURRENT salary (unchanged meaning); starting_salary is a
--    permanent snapshot of what they were hired at. Applying an increment
--    inserts a salary_increments row AND updates employees.salary — same
--    "snapshot the inputs, then move the live total" pattern already used
--    for advance_deductions/salary_payments elsewhere in this schema.
--    Increments are never deleted once applied (a correction is a new
--    increment, same as any real payroll system) — no delete needed.
--
-- 2. Cash ledger integration for Advances and Salary Payments: these have
--    never posted to cash_transactions, so a cash advance or cash salary
--    payment never reduced Office Cash Balance even though real cash left
--    the office. Fixed the same way expenses/creditor payments already
--    work: payment_method = 'Cash' posts a linked cash_transactions
--    cash-out entry; any other payment_method requires a reference_number
--    instead and never touches cash.
--
-- Safe to re-run.

alter table employees add column if not exists starting_salary numeric(12,2);
update employees set starting_salary = salary where starting_salary is null;
alter table employees alter column starting_salary set not null;
alter table employees alter column starting_salary set default 0;

create table if not exists salary_increments (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id) on delete cascade,
  increment_date date not null default current_date,
  previous_salary numeric(12,2) not null,
  increment_type text not null check (increment_type in ('fixed', 'percentage')),
  increment_value numeric(12,2) not null check (increment_value > 0),
  increment_amount numeric(12,2) not null,
  new_salary numeric(12,2) not null,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_salary_increments_employee on salary_increments(employee_id);

drop trigger if exists audit_salary_increments on salary_increments;
create trigger audit_salary_increments before insert or update or delete on salary_increments for each row execute function stamp_and_log_audit();

alter table salary_increments enable row level security;
drop policy if exists "authenticated app users only" on salary_increments;
create policy "authenticated app users only" on salary_increments for all using (is_app_user()) with check (is_app_user());

alter table advances add column if not exists reference_number text;
alter table salary_payments add column if not exists reference_number text;

alter table cash_transactions drop constraint if exists cash_transactions_reference_type_check;
alter table cash_transactions add constraint cash_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'bank_withdrawal', 'expense', 'other', 'courier_collection', 'cash_transfer', 'creditor_payment', 'advance', 'salary_payment'));
