-- Protees Business Manager — Creditors & Supplier Ledger.
--
-- A creditor is anyone the business owes money to (a supplier/vendor with
-- an outstanding balance). Category is free text, driven by the
-- 'creditor_category' Master Data type (see migration_016) — the admin
-- can add new categories from Settings without a deploy.
--
-- Outstanding balance is never stored — it's computed the same way as
-- every other ledger in this app (advances, courier collections): opening
-- balance + sum(bills) - sum(payments), derived live in CollectionsContext.
--
-- A bill increases what we owe (a purchase/invoice not yet paid) and never
-- touches cash/bank. A payment reduces what we owe AND posts a matching
-- cash_transactions cash-out (if paid from Office Cash) or bank_transactions
-- debit (if paid from a specific bank account) — mirroring exactly how
-- courier_collections posts to cash/bank, just in the opposite direction
-- (money going out, not coming in).
--
-- Safe to re-run.

create table if not exists creditors (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  contact_person text,
  phone text,
  address text,
  notes text,
  opening_balance numeric(12,2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);

create table if not exists creditor_bills (
  id bigint generated by default as identity primary key,
  creditor_id bigint not null references creditors(id) on delete cascade,
  bill_date date not null default current_date,
  amount numeric(12,2) not null check (amount > 0),
  description text,
  reference_number text,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_creditor_bills_creditor on creditor_bills(creditor_id);

create table if not exists creditor_payments (
  id bigint generated by default as identity primary key,
  creditor_id bigint not null references creditors(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  payment_date date not null default current_date,
  payment_type text not null check (payment_type in ('cash', 'bank_transfer')),
  bank_account_id bigint references bank_accounts(id),
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz,
  constraint creditor_payments_bank_required check (
    (payment_type = 'bank_transfer' and bank_account_id is not null) or
    (payment_type = 'cash' and bank_account_id is null)
  )
);
create index if not exists idx_creditor_payments_creditor on creditor_payments(creditor_id);

-- Allow creditor_payment as a reference_type on the shared cash/bank ledgers
-- (widening the existing constraint, not replacing its earlier additions).
alter table cash_transactions drop constraint if exists cash_transactions_reference_type_check;
alter table cash_transactions add constraint cash_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'bank_withdrawal', 'expense', 'other', 'courier_collection', 'cash_transfer', 'creditor_payment'));

alter table bank_transactions drop constraint if exists bank_transactions_reference_type_check;
alter table bank_transactions add constraint bank_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'cash_withdrawal', 'manual', 'courier_collection', 'cash_transfer', 'creditor_payment'));

drop trigger if exists audit_creditors on creditors;
create trigger audit_creditors before insert or update or delete on creditors for each row execute function stamp_and_log_audit();

drop trigger if exists audit_creditor_bills on creditor_bills;
create trigger audit_creditor_bills before insert or update or delete on creditor_bills for each row execute function stamp_and_log_audit();

drop trigger if exists audit_creditor_payments on creditor_payments;
create trigger audit_creditor_payments before insert or update or delete on creditor_payments for each row execute function stamp_and_log_audit();

alter table creditors enable row level security;
alter table creditor_bills enable row level security;
alter table creditor_payments enable row level security;

drop policy if exists "authenticated app users only" on creditors;
create policy "authenticated app users only" on creditors for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on creditor_bills;
create policy "authenticated app users only" on creditor_bills for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on creditor_payments;
create policy "authenticated app users only" on creditor_payments for all using (is_app_user()) with check (is_app_user());
