-- Protees Business Manager — Protees Unit / Cutting Department redesign
-- Additive only: every statement either creates a new table/column with
-- "if not exists" or adds a column with a safe default. Nothing here drops
-- or rewrites existing rows in employees, advances, expenses, or
-- salary_payments.

-- ---------------------------------------------------------------------------
-- Cutting Department: employees gain a join date
-- ---------------------------------------------------------------------------
alter table employees add column if not exists join_date date;

-- ---------------------------------------------------------------------------
-- Advances now carry a department + optional notes, so the same table can
-- serve both the Cutting Department (employees) and Protees Unit (supervisor).
-- Existing rows backfill to 'cutting_department', which matches reality —
-- every advance recorded so far was for a Cutting Department employee.
-- ---------------------------------------------------------------------------
alter table advances add column if not exists department text not null default 'cutting_department';
alter table advances add column if not exists notes text;
alter table advances drop constraint if exists advances_department_check;
alter table advances add constraint advances_department_check
  check (department in ('cutting_department', 'protees_unit'));

-- ---------------------------------------------------------------------------
-- Expenses become "Unit Expenses" — every expense in this app belongs to
-- Protees Unit, so we just add the category list + notes rather than create
-- a parallel table.
-- ---------------------------------------------------------------------------
alter table expenses add column if not exists category text not null default 'Other Expenses';
alter table expenses add column if not exists notes text;
alter table expenses drop constraint if exists expenses_category_check;
alter table expenses add constraint expenses_category_check
  check (category in ('Thread', 'Fabric', 'Packing', 'Transport', 'Printing', 'Other Expenses'));

-- ---------------------------------------------------------------------------
-- Salary payments (Cutting Department, monthly) gain an overtime component.
-- Net = base + overtime - deduction, computed by the app on every insert.
-- ---------------------------------------------------------------------------
alter table salary_payments add column if not exists overtime_amount numeric(12,2) not null default 0;

-- ---------------------------------------------------------------------------
-- Supervisors — Protees Unit is managed by a single supervisor. Kept as its
-- own small table (same pattern as employees) so voice input and dropdowns
-- have a name to match against.
-- ---------------------------------------------------------------------------
create table if not exists supervisors (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Unit payments — Protees Unit's bi-weekly payment cycle.
-- Net amount (total - advance given) is computed and stored by the app,
-- the same pattern already used for salary_payments.net_amount.
-- ---------------------------------------------------------------------------
create table if not exists unit_payments (
  id bigint generated by default as identity primary key,
  supervisor_name text not null,
  payment_date date not null default current_date,
  period_start date not null,
  period_end date not null,
  total_amount numeric(12,2) not null default 0,
  advance_given numeric(12,2) not null default 0,
  net_amount numeric(12,2) not null default 0,
  unit_expenses_during_period numeric(12,2) not null default 0,
  notes text,
  month int not null,
  year int not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Advance deductions now also carry department, and can link back to either
-- a salary_payments row (Cutting Department) or a unit_payments row
-- (Protees Unit) — exactly one of the two will be set per row.
-- ---------------------------------------------------------------------------
alter table advance_deductions add column if not exists department text not null default 'cutting_department';
alter table advance_deductions add column if not exists unit_payment_id bigint references unit_payments(id) on delete cascade;

create index if not exists idx_advances_department on advances(department);
create index if not exists idx_advance_deductions_department on advance_deductions(department);
create index if not exists idx_unit_payments_supervisor_name on unit_payments(supervisor_name);
create index if not exists idx_unit_payments_period on unit_payments(period_start, period_end);

-- ---------------------------------------------------------------------------
-- View: outstanding advance balance per (name, department) — generalizes the
-- old employee_advance_balance view across both departments.
-- ---------------------------------------------------------------------------
create or replace view advance_balance_by_name as
select
  coalesce(adv.employee_name, ded.employee_name) as name,
  coalesce(adv.department, ded.department) as department,
  coalesce(adv.total_advanced, 0) as total_advanced,
  coalesce(ded.total_deducted, 0) as total_deducted,
  coalesce(adv.total_advanced, 0) - coalesce(ded.total_deducted, 0) as balance
from (
  select employee_name, department, sum(amount) as total_advanced
  from advances
  group by employee_name, department
) adv
full outer join (
  select employee_name, department, sum(amount) as total_deducted
  from advance_deductions
  group by employee_name, department
) ded on ded.employee_name = adv.employee_name and ded.department = adv.department;

-- ---------------------------------------------------------------------------
-- Row Level Security for the two new tables (same permissive policy as
-- every other table in this app).
-- ---------------------------------------------------------------------------
alter table supervisors enable row level security;
alter table unit_payments enable row level security;

drop policy if exists "allow all" on supervisors;
drop policy if exists "allow all" on unit_payments;

create policy "allow all" on supervisors for all using (true) with check (true);
create policy "allow all" on unit_payments for all using (true) with check (true);
