-- Protees Business Manager — Factory / Unit Production module, Phase 1
-- Adds: Factory-only authentication (profiles + role), Product setup
-- (sizes/colors/operations/rate history), and Production Plans.
--
-- IMPORTANT — scope of auth: this ONLY gates the new /factory/* routes.
-- Every existing table (employees, advances, expenses, salary_payments,
-- unit_payments, etc.) is untouched and keeps its current "allow all"
-- policies exactly as-is. This migration adds new tables only — nothing
-- existing is altered, dropped, or renamed. Safe to re-run.

-- ---------------------------------------------------------------------------
-- Factory user profiles — one row per Supabase Auth user, added by a
-- trigger the moment they sign up. `role` starts NULL ("pending approval")
-- until an admin assigns one from the Team Members screen.
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text check (role in ('admin', 'cutting_head', 'stitching_head', 'quality_head', 'store_manager')),
  created_at timestamptz not null default now()
);

create or replace function public.factory_role()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role from profiles where id = auth.uid();
$$;

create or replace function public.handle_new_factory_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email), null)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_factory_user();

alter table profiles enable row level security;
drop policy if exists "read own or admin reads all" on profiles;
drop policy if exists "admin writes all" on profiles;
create policy "read own or admin reads all" on profiles
  for select using (auth.uid() = id or factory_role() = 'admin');
create policy "admin writes all" on profiles
  for update using (factory_role() = 'admin') with check (factory_role() = 'admin');

-- ---------------------------------------------------------------------------
-- Global color catalog — admin-extendable, shared across products.
-- ---------------------------------------------------------------------------
create table if not exists colors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  hex text not null default '#64748b',
  created_at timestamptz not null default now()
);
insert into colors (name, hex) values
  ('Black', '#0f172a'),
  ('White', '#f8fafc'),
  ('Red', '#ef4444'),
  ('Blue', '#3b82f6'),
  ('Navy', '#1e3a8a'),
  ('Grey', '#6b7280')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Products — admin-configured. `production_type` decides whether a plan
-- for this product routes through Digital Print before Cutting.
-- ---------------------------------------------------------------------------
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  picture_url text,
  production_type text not null default 'normal' check (production_type in ('normal', 'digital_print')),
  size_group text not null default 'adult' check (size_group in ('adult', 'kids')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  size_label text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (product_id, size_label)
);

create table if not exists product_colors (
  product_id bigint not null references products(id) on delete cascade,
  color_id bigint not null references colors(id) on delete cascade,
  primary key (product_id, color_id)
);

-- Operations are grouped under a free-text department label (Overlock,
-- Flat Lock, Singer, Clipping, ...) chosen per product by Admin — never a
-- fixed list, since different products need entirely different operations.
create table if not exists product_operations (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  department_label text not null,
  operation_name text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Rate history: a rate is NEVER updated in place. Changing a rate inserts a
-- new row with effective_from = now(); the "current" rate is the latest row
-- per operation. Historical production always snapshots the rate that was
-- current at completion time, so old records never move.
create table if not exists product_operation_rates (
  id bigint generated by default as identity primary key,
  product_operation_id bigint not null references product_operations(id) on delete cascade,
  rate numeric(12,2) not null check (rate >= 0),
  effective_from timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists idx_product_operation_rates_op on product_operation_rates(product_operation_id, effective_from desc);

create or replace view product_operation_current_rates as
select distinct on (product_operation_id)
  product_operation_id,
  rate,
  effective_from
from product_operation_rates
order by product_operation_id, effective_from desc;

-- ---------------------------------------------------------------------------
-- Production Plans — Admin creates. Only relevant (configured) sizes for
-- the chosen product should be offered by the UI.
-- ---------------------------------------------------------------------------
create table if not exists production_plans (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id),
  color_id bigint references colors(id),
  production_type text not null default 'normal' check (production_type in ('normal', 'digital_print')),
  plan_date date not null default current_date,
  expected_completion_date date,
  remarks text,
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'completed', 'cancelled')),
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists production_plan_sizes (
  id bigint generated by default as identity primary key,
  production_plan_id bigint not null references production_plans(id) on delete cascade,
  size_label text not null,
  planned_qty int not null check (planned_qty >= 0),
  unique (production_plan_id, size_label)
);

create index if not exists idx_production_plans_status on production_plans(status);
create index if not exists idx_production_plan_sizes_plan on production_plan_sizes(production_plan_id);

-- ---------------------------------------------------------------------------
-- Row Level Security — factory tables only. Any signed-in user with an
-- approved role (profiles.role is not null) can read; only admin can write
-- product/operation/rate/plan configuration, matching "workers never touch
-- rates" at the database level, not just in the UI.
-- ---------------------------------------------------------------------------
alter table colors enable row level security;
alter table products enable row level security;
alter table product_sizes enable row level security;
alter table product_colors enable row level security;
alter table product_operations enable row level security;
alter table product_operation_rates enable row level security;
alter table production_plans enable row level security;
alter table production_plan_sizes enable row level security;

drop policy if exists "factory read" on colors;
drop policy if exists "admin write" on colors;
create policy "factory read" on colors for select using (factory_role() is not null);
create policy "admin write" on colors for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on products;
drop policy if exists "admin write" on products;
create policy "factory read" on products for select using (factory_role() is not null);
create policy "admin write" on products for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_sizes;
drop policy if exists "admin write" on product_sizes;
create policy "factory read" on product_sizes for select using (factory_role() is not null);
create policy "admin write" on product_sizes for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_colors;
drop policy if exists "admin write" on product_colors;
create policy "factory read" on product_colors for select using (factory_role() is not null);
create policy "admin write" on product_colors for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_operations;
drop policy if exists "admin write" on product_operations;
create policy "factory read" on product_operations for select using (factory_role() is not null);
create policy "admin write" on product_operations for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_operation_rates;
drop policy if exists "admin write" on product_operation_rates;
create policy "factory read" on product_operation_rates for select using (factory_role() is not null);
create policy "admin write" on product_operation_rates for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on production_plans;
drop policy if exists "admin write" on production_plans;
create policy "factory read" on production_plans for select using (factory_role() is not null);
create policy "admin write" on production_plans for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on production_plan_sizes;
drop policy if exists "admin write" on production_plan_sizes;
create policy "factory read" on production_plan_sizes for select using (factory_role() is not null);
create policy "admin write" on production_plan_sizes for all using (factory_role() = 'admin') with check (factory_role() = 'admin');
