-- Protees Business Manager — full schema
-- Two business units:
--   Protees Unit        — one supervisor, bi-weekly payments, unit expenses
--   Cutting Department   — employees, monthly salary + overtime + advances
-- No employee_id-style foreign keys for people — names (text) are the join
-- key everywhere, matching how this app's data is actually keyed. Safe to
-- run on a fresh database or on top of the existing tables — every
-- statement is idempotent.

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  salary numeric(12,2) not null default 0,
  join_date date,
  created_at timestamptz not null default now()
);
alter table employees add column if not exists join_date date;

create table if not exists supervisors (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Advances — shared by both departments, disambiguated by `department`.
-- ---------------------------------------------------------------------------
create table if not exists advances (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  department text not null default 'cutting_department',
  amount numeric(12,2) not null check (amount > 0),
  payment_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table advances add column if not exists department text not null default 'cutting_department';
alter table advances add column if not exists notes text;
alter table advances drop constraint if exists advances_department_check;
alter table advances add constraint advances_department_check
  check (department in ('cutting_department', 'protees_unit'));

-- ---------------------------------------------------------------------------
-- Unit Expenses (Protees Unit) — table name stays `expenses` for continuity.
-- ---------------------------------------------------------------------------
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'Other Expenses',
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table expenses add column if not exists category text not null default 'Other Expenses';
alter table expenses add column if not exists notes text;
-- Categories are database-driven (see expense_categories below) — no fixed
-- check constraint on this column.
alter table expenses drop constraint if exists expenses_category_check;

-- ---------------------------------------------------------------------------
-- Expense categories — database-driven, so new categories added from the
-- app (via "+ Add New Category") need no code changes.
-- ---------------------------------------------------------------------------
create table if not exists expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
insert into expense_categories (name) values
  ('Thread'),
  ('Fabric'),
  ('Packing'),
  ('Transport'),
  ('Printing'),
  ('Khadim Hussain'),
  ('Food Grocery'),
  ('Food Vegetable'),
  ('Rotiyan'),
  ('Gas'),
  ('Diesel'),
  ('Transportation'),
  ('Other Expenses')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Khadim Hussain Account — a running ledger of money given to Khadim
-- Hussain for unit material purchases (Payment Given) vs. bills he submits
-- against it (Bill Submitted). Balance = payments given - bills submitted.
-- ---------------------------------------------------------------------------
create table if not exists khadim_transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('payment_given', 'bill_submitted')),
  date date not null default current_date,
  amount numeric(12,2) not null check (amount > 0),
  notes text,
  description text,
  created_at timestamptz not null default now()
);
create index if not exists idx_khadim_transactions_date on khadim_transactions(date);

-- ---------------------------------------------------------------------------
-- Salary payments — Cutting Department, monthly.
-- Net = base + overtime - deduction (computed by the app on insert).
-- ---------------------------------------------------------------------------
create table if not exists salary_payments (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  base_amount numeric(12,2) not null,
  overtime_amount numeric(12,2) not null default 0,
  deduction_amount numeric(12,2) not null default 0,
  net_amount numeric(12,2) not null,
  month int not null check (month between 1 and 12),
  year int not null,
  payment_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table salary_payments add column if not exists overtime_amount numeric(12,2) not null default 0;

-- ---------------------------------------------------------------------------
-- Unit payments — Protees Unit, bi-weekly.
-- Net = total - advance given (computed by the app on insert).
-- ---------------------------------------------------------------------------
create table if not exists unit_payments (
  id bigint generated by default as identity primary key,
  supervisor_name text not null,
  payment_date date not null default current_date,
  period_start date not null,
  period_end date not null,
  total_amount numeric(12,2) not null default 0,
  overtime_amount numeric(12,2) not null default 0,
  advance_given numeric(12,2) not null default 0,
  net_amount numeric(12,2) not null default 0,
  unit_expenses_during_period numeric(12,2) not null default 0,
  notes text,
  month int not null,
  year int not null,
  created_at timestamptz not null default now()
);
alter table unit_payments add column if not exists overtime_amount numeric(12,2) not null default 0;

-- ---------------------------------------------------------------------------
-- Advance deductions — links a payment (salary OR unit) back to the
-- advance(s) it paid down. Exactly one of salary_payment_id / unit_payment_id
-- is set per row.
-- ---------------------------------------------------------------------------
create table if not exists advance_deductions (
  id bigint generated by default as identity primary key,
  advance_id bigint references advances(id) on delete set null,
  employee_name text not null,
  department text not null default 'cutting_department',
  salary_payment_id bigint references salary_payments(id) on delete cascade,
  unit_payment_id bigint references unit_payments(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  created_at timestamptz not null default now()
);
alter table advance_deductions add column if not exists department text not null default 'cutting_department';
alter table advance_deductions add column if not exists unit_payment_id bigint references unit_payments(id) on delete cascade;

-- ---------------------------------------------------------------------------
-- Units — legacy branch/location registry (kept for continuity; the Protees
-- Unit module above is now the primary way this business is modeled).
-- ---------------------------------------------------------------------------
create table if not exists units (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  created_at timestamptz not null default now()
);

create index if not exists idx_advances_employee_name on advances(employee_name);
create index if not exists idx_advances_department on advances(department);
create index if not exists idx_salary_payments_employee_name on salary_payments(employee_name);
create index if not exists idx_advance_deductions_employee_name on advance_deductions(employee_name);
create index if not exists idx_advance_deductions_department on advance_deductions(department);
create index if not exists idx_unit_payments_supervisor_name on unit_payments(supervisor_name);
create index if not exists idx_unit_payments_period on unit_payments(period_start, period_end);

-- ---------------------------------------------------------------------------
-- View: outstanding advance balance per (name, department)
-- ---------------------------------------------------------------------------
create or replace view advance_balance_by_name as
select
  coalesce(adv.employee_name, ded.employee_name) as name,
  coalesce(adv.department, ded.department) as department,
  coalesce(adv.total_advanced, 0) as total_advanced,
  coalesce(ded.total_deducted, 0) as total_deducted,
  coalesce(adv.total_advanced, 0) - coalesce(ded.total_deducted, 0) as balance
from (
  select employee_name, department, sum(amount) as total_advanced
  from advances
  group by employee_name, department
) adv
full outer join (
  select employee_name, department, sum(amount) as total_deducted
  from advance_deductions
  group by employee_name, department
) ded on ded.employee_name = adv.employee_name and ded.department = adv.department;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- This app is a single-tenant internal tool used with the Supabase publishable
-- (anon) key. These policies allow full read/write access. Replace with
-- auth-scoped policies before exposing this publicly.
-- ---------------------------------------------------------------------------
alter table employees enable row level security;
alter table supervisors enable row level security;
alter table advances enable row level security;
alter table expenses enable row level security;
alter table salary_payments enable row level security;
alter table unit_payments enable row level security;
alter table advance_deductions enable row level security;
alter table units enable row level security;
alter table khadim_transactions enable row level security;
alter table expense_categories enable row level security;

drop policy if exists "allow all" on employees;
drop policy if exists "allow all" on supervisors;
drop policy if exists "allow all" on advances;
drop policy if exists "allow all" on expenses;
drop policy if exists "allow all" on salary_payments;
drop policy if exists "allow all" on unit_payments;
drop policy if exists "allow all" on advance_deductions;
drop policy if exists "allow all" on units;
drop policy if exists "allow all" on khadim_transactions;
drop policy if exists "allow all" on expense_categories;

create policy "allow all" on employees for all using (true) with check (true);
create policy "allow all" on supervisors for all using (true) with check (true);
create policy "allow all" on advances for all using (true) with check (true);
create policy "allow all" on expenses for all using (true) with check (true);
create policy "allow all" on salary_payments for all using (true) with check (true);
create policy "allow all" on unit_payments for all using (true) with check (true);
create policy "allow all" on advance_deductions for all using (true) with check (true);
create policy "allow all" on units for all using (true) with check (true);
create policy "allow all" on khadim_transactions for all using (true) with check (true);
create policy "allow all" on expense_categories for all using (true) with check (true);
