-- Protees Business Manager — full schema
-- Two business units:
--   Protees Unit        — one supervisor, bi-weekly payments, unit expenses
--   Cutting Department   — employees, monthly salary + overtime + advances
-- No employee_id-style foreign keys for people — names (text) are the join
-- key everywhere, matching how this app's data is actually keyed. Safe to
-- run on a fresh database or on top of the existing tables — every
-- statement is idempotent.

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  salary numeric(12,2) not null default 0,
  join_date date,
  created_at timestamptz not null default now()
);
alter table employees add column if not exists join_date date;

create table if not exists supervisors (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Advances — shared by both departments, disambiguated by `department`.
-- ---------------------------------------------------------------------------
create table if not exists advances (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  department text not null default 'cutting_department',
  amount numeric(12,2) not null check (amount > 0),
  payment_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table advances add column if not exists department text not null default 'cutting_department';
alter table advances add column if not exists notes text;
alter table advances drop constraint if exists advances_department_check;
alter table advances add constraint advances_department_check
  check (department in ('cutting_department', 'protees_unit'));

-- ---------------------------------------------------------------------------
-- Unit Expenses (Protees Unit) — table name stays `expenses` for continuity.
-- ---------------------------------------------------------------------------
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'Other Expenses',
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table expenses add column if not exists category text not null default 'Other Expenses';
alter table expenses add column if not exists notes text;
-- Categories are database-driven (see expense_categories below) — no fixed
-- check constraint on this column.
alter table expenses drop constraint if exists expenses_category_check;

-- ---------------------------------------------------------------------------
-- Expense categories — database-driven, so new categories added from the
-- app (via "+ Add New Category") need no code changes.
-- ---------------------------------------------------------------------------
create table if not exists expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
insert into expense_categories (name) values
  ('Thread'),
  ('Fabric'),
  ('Packing'),
  ('Transport'),
  ('Printing'),
  ('Khadim Hussain'),
  ('Food Grocery'),
  ('Food Vegetable'),
  ('Rotiyan'),
  ('Gas'),
  ('Diesel'),
  ('Transportation'),
  ('Other Expenses')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Khadim Hussain Account — a running ledger of money given to Khadim
-- Hussain for unit material purchases (Payment Given) vs. bills he submits
-- against it (Bill Submitted). Balance = payments given - bills submitted.
-- ---------------------------------------------------------------------------
create table if not exists khadim_transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('payment_given', 'bill_submitted')),
  date date not null default current_date,
  amount numeric(12,2) not null check (amount > 0),
  notes text,
  description text,
  created_at timestamptz not null default now()
);
create index if not exists idx_khadim_transactions_date on khadim_transactions(date);

-- ---------------------------------------------------------------------------
-- Salary payments — Cutting Department, monthly.
-- Net = base + overtime - deduction (computed by the app on insert).
-- ---------------------------------------------------------------------------
create table if not exists salary_payments (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  base_amount numeric(12,2) not null,
  overtime_amount numeric(12,2) not null default 0,
  deduction_amount numeric(12,2) not null default 0,
  net_amount numeric(12,2) not null,
  month int not null check (month between 1 and 12),
  year int not null,
  payment_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table salary_payments add column if not exists overtime_amount numeric(12,2) not null default 0;

-- ---------------------------------------------------------------------------
-- Unit payments — Protees Unit, bi-weekly.
-- Net = total - advance given (computed by the app on insert).
-- ---------------------------------------------------------------------------
create table if not exists unit_payments (
  id bigint generated by default as identity primary key,
  supervisor_name text not null,
  payment_date date not null default current_date,
  period_start date not null,
  period_end date not null,
  total_amount numeric(12,2) not null default 0,
  overtime_amount numeric(12,2) not null default 0,
  advance_given numeric(12,2) not null default 0,
  net_amount numeric(12,2) not null default 0,
  unit_expenses_during_period numeric(12,2) not null default 0,
  notes text,
  month int not null,
  year int not null,
  created_at timestamptz not null default now()
);
alter table unit_payments add column if not exists overtime_amount numeric(12,2) not null default 0;

-- ---------------------------------------------------------------------------
-- Advance deductions — links a payment (salary OR unit) back to the
-- advance(s) it paid down. Exactly one of salary_payment_id / unit_payment_id
-- is set per row.
-- ---------------------------------------------------------------------------
create table if not exists advance_deductions (
  id bigint generated by default as identity primary key,
  advance_id bigint references advances(id) on delete set null,
  employee_name text not null,
  department text not null default 'cutting_department',
  salary_payment_id bigint references salary_payments(id) on delete cascade,
  unit_payment_id bigint references unit_payments(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  created_at timestamptz not null default now()
);
alter table advance_deductions add column if not exists department text not null default 'cutting_department';
alter table advance_deductions add column if not exists unit_payment_id bigint references unit_payments(id) on delete cascade;

-- ---------------------------------------------------------------------------
-- Units — legacy branch/location registry (kept for continuity; the Protees
-- Unit module above is now the primary way this business is modeled).
-- ---------------------------------------------------------------------------
create table if not exists units (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  created_at timestamptz not null default now()
);

create index if not exists idx_advances_employee_name on advances(employee_name);
create index if not exists idx_advances_department on advances(department);
create index if not exists idx_salary_payments_employee_name on salary_payments(employee_name);
create index if not exists idx_advance_deductions_employee_name on advance_deductions(employee_name);
create index if not exists idx_advance_deductions_department on advance_deductions(department);
create index if not exists idx_unit_payments_supervisor_name on unit_payments(supervisor_name);
create index if not exists idx_unit_payments_period on unit_payments(period_start, period_end);

-- ---------------------------------------------------------------------------
-- View: outstanding advance balance per (name, department)
-- ---------------------------------------------------------------------------
create or replace view advance_balance_by_name as
select
  coalesce(adv.employee_name, ded.employee_name) as name,
  coalesce(adv.department, ded.department) as department,
  coalesce(adv.total_advanced, 0) as total_advanced,
  coalesce(ded.total_deducted, 0) as total_deducted,
  coalesce(adv.total_advanced, 0) - coalesce(ded.total_deducted, 0) as balance
from (
  select employee_name, department, sum(amount) as total_advanced
  from advances
  group by employee_name, department
) adv
full outer join (
  select employee_name, department, sum(amount) as total_deducted
  from advance_deductions
  group by employee_name, department
) ded on ded.employee_name = adv.employee_name and ded.department = adv.department;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- This app is a single-tenant internal tool used with the Supabase publishable
-- (anon) key. These policies allow full read/write access. Replace with
-- auth-scoped policies before exposing this publicly.
-- ---------------------------------------------------------------------------
alter table employees enable row level security;
alter table supervisors enable row level security;
alter table advances enable row level security;
alter table expenses enable row level security;
alter table salary_payments enable row level security;
alter table unit_payments enable row level security;
alter table advance_deductions enable row level security;
alter table units enable row level security;
alter table khadim_transactions enable row level security;
alter table expense_categories enable row level security;

drop policy if exists "allow all" on employees;
drop policy if exists "allow all" on supervisors;
drop policy if exists "allow all" on advances;
drop policy if exists "allow all" on expenses;
drop policy if exists "allow all" on salary_payments;
drop policy if exists "allow all" on unit_payments;
drop policy if exists "allow all" on advance_deductions;
drop policy if exists "allow all" on units;
drop policy if exists "allow all" on khadim_transactions;
drop policy if exists "allow all" on expense_categories;

create policy "allow all" on employees for all using (true) with check (true);
create policy "allow all" on supervisors for all using (true) with check (true);
create policy "allow all" on advances for all using (true) with check (true);
create policy "allow all" on expenses for all using (true) with check (true);
create policy "allow all" on salary_payments for all using (true) with check (true);
create policy "allow all" on unit_payments for all using (true) with check (true);
create policy "allow all" on advance_deductions for all using (true) with check (true);
create policy "allow all" on units for all using (true) with check (true);
create policy "allow all" on khadim_transactions for all using (true) with check (true);
create policy "allow all" on expense_categories for all using (true) with check (true);

-- =============================================================================
-- FACTORY / UNIT PRODUCTION MODULE (Phase 1) — appended from migration_006
-- =============================================================================

-- Protees Business Manager — Factory / Unit Production module, Phase 1
-- Adds: Factory-only authentication (profiles + role), Product setup
-- (sizes/colors/operations/rate history), and Production Plans.
--
-- IMPORTANT — scope of auth: this ONLY gates the new /factory/* routes.
-- Every existing table (employees, advances, expenses, salary_payments,
-- unit_payments, etc.) is untouched and keeps its current "allow all"
-- policies exactly as-is. This migration adds new tables only — nothing
-- existing is altered, dropped, or renamed. Safe to re-run.

-- ---------------------------------------------------------------------------
-- Factory user profiles — one row per Supabase Auth user, added by a
-- trigger the moment they sign up. `role` starts NULL ("pending approval")
-- until an admin assigns one from the Team Members screen.
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text check (role in ('admin', 'cutting_head', 'stitching_head', 'quality_head', 'store_manager')),
  created_at timestamptz not null default now()
);

create or replace function public.factory_role()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role from profiles where id = auth.uid();
$$;

create or replace function public.handle_new_factory_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email), null)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_factory_user();

alter table profiles enable row level security;
drop policy if exists "read own or admin reads all" on profiles;
drop policy if exists "admin writes all" on profiles;
create policy "read own or admin reads all" on profiles
  for select using (auth.uid() = id or factory_role() = 'admin');
create policy "admin writes all" on profiles
  for update using (factory_role() = 'admin') with check (factory_role() = 'admin');

-- ---------------------------------------------------------------------------
-- Global color catalog — admin-extendable, shared across products.
-- ---------------------------------------------------------------------------
create table if not exists colors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  hex text not null default '#64748b',
  created_at timestamptz not null default now()
);
insert into colors (name, hex) values
  ('Black', '#0f172a'),
  ('White', '#f8fafc'),
  ('Red', '#ef4444'),
  ('Blue', '#3b82f6'),
  ('Navy', '#1e3a8a'),
  ('Grey', '#6b7280')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Products — admin-configured. `production_type` decides whether a plan
-- for this product routes through Digital Print before Cutting.
-- ---------------------------------------------------------------------------
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  picture_url text,
  production_type text not null default 'normal' check (production_type in ('normal', 'digital_print')),
  size_group text not null default 'adult' check (size_group in ('adult', 'kids')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  size_label text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (product_id, size_label)
);

create table if not exists product_colors (
  product_id bigint not null references products(id) on delete cascade,
  color_id bigint not null references colors(id) on delete cascade,
  primary key (product_id, color_id)
);

-- Operations are grouped under a free-text department label (Overlock,
-- Flat Lock, Singer, Clipping, ...) chosen per product by Admin — never a
-- fixed list, since different products need entirely different operations.
create table if not exists product_operations (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  department_label text not null,
  operation_name text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Rate history: a rate is NEVER updated in place. Changing a rate inserts a
-- new row with effective_from = now(); the "current" rate is the latest row
-- per operation. Historical production always snapshots the rate that was
-- current at completion time, so old records never move.
create table if not exists product_operation_rates (
  id bigint generated by default as identity primary key,
  product_operation_id bigint not null references product_operations(id) on delete cascade,
  rate numeric(12,2) not null check (rate >= 0),
  effective_from timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists idx_product_operation_rates_op on product_operation_rates(product_operation_id, effective_from desc);

create or replace view product_operation_current_rates as
select distinct on (product_operation_id)
  product_operation_id,
  rate,
  effective_from
from product_operation_rates
order by product_operation_id, effective_from desc;

-- ---------------------------------------------------------------------------
-- Production Plans — Admin creates. Only relevant (configured) sizes for
-- the chosen product should be offered by the UI.
-- ---------------------------------------------------------------------------
create table if not exists production_plans (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id),
  color_id bigint references colors(id),
  production_type text not null default 'normal' check (production_type in ('normal', 'digital_print')),
  plan_date date not null default current_date,
  expected_completion_date date,
  remarks text,
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'completed', 'cancelled')),
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists production_plan_sizes (
  id bigint generated by default as identity primary key,
  production_plan_id bigint not null references production_plans(id) on delete cascade,
  size_label text not null,
  planned_qty int not null check (planned_qty >= 0),
  unique (production_plan_id, size_label)
);

create index if not exists idx_production_plans_status on production_plans(status);
create index if not exists idx_production_plan_sizes_plan on production_plan_sizes(production_plan_id);

-- ---------------------------------------------------------------------------
-- Row Level Security — factory tables only. Any signed-in user with an
-- approved role (profiles.role is not null) can read; only admin can write
-- product/operation/rate/plan configuration, matching "workers never touch
-- rates" at the database level, not just in the UI.
-- ---------------------------------------------------------------------------
alter table colors enable row level security;
alter table products enable row level security;
alter table product_sizes enable row level security;
alter table product_colors enable row level security;
alter table product_operations enable row level security;
alter table product_operation_rates enable row level security;
alter table production_plans enable row level security;
alter table production_plan_sizes enable row level security;

drop policy if exists "factory read" on colors;
drop policy if exists "admin write" on colors;
create policy "factory read" on colors for select using (factory_role() is not null);
create policy "admin write" on colors for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on products;
drop policy if exists "admin write" on products;
create policy "factory read" on products for select using (factory_role() is not null);
create policy "admin write" on products for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_sizes;
drop policy if exists "admin write" on product_sizes;
create policy "factory read" on product_sizes for select using (factory_role() is not null);
create policy "admin write" on product_sizes for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_colors;
drop policy if exists "admin write" on product_colors;
create policy "factory read" on product_colors for select using (factory_role() is not null);
create policy "admin write" on product_colors for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_operations;
drop policy if exists "admin write" on product_operations;
create policy "factory read" on product_operations for select using (factory_role() is not null);
create policy "admin write" on product_operations for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_operation_rates;
drop policy if exists "admin write" on product_operation_rates;
create policy "factory read" on product_operation_rates for select using (factory_role() is not null);
create policy "admin write" on product_operation_rates for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on production_plans;
drop policy if exists "admin write" on production_plans;
create policy "factory read" on production_plans for select using (factory_role() is not null);
create policy "admin write" on production_plans for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on production_plan_sizes;
drop policy if exists "admin write" on production_plan_sizes;
create policy "factory read" on production_plan_sizes for select using (factory_role() is not null);
create policy "admin write" on production_plan_sizes for all using (factory_role() = 'admin') with check (factory_role() = 'admin');


-- =============================================================================
-- Main-app authentication + audit trail (see migration_007_auth_and_audit.sql)
-- =============================================================================

-- Protees Business Manager — main-app authentication + full audit trail
--
-- Adds:
--   1. app_users: maps a fixed username (aqeel/arslan) to a Supabase Auth
--      account, so the main app can offer username-based login while
--      Supabase Auth itself still authenticates by email under the hood.
--   2. audit_log: an append-only record of every create/update/delete
--      across the business tables, including a full snapshot of deleted
--      rows (which otherwise vanish with no trace).
--   3. created_by_user_id / created_by_username / updated_by_user_id /
--      updated_by_username / updated_at columns on every business table,
--      auto-stamped by a trigger — no frontend code has to set these.
--   4. RLS on the business tables tightened from "allow all" to
--      "must be a row in app_users" — closing the anon-key-can-write-
--      anything gap now that the app has real logins.
--
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / OR
-- REPLACE / DROP POLICY IF EXISTS). Existing rows are untouched — the new
-- columns come in NULL for pre-existing records, which is expected (see
-- migration notes shared with the user).
--
-- Does NOT touch: the Factory module (profiles, colors, products,
-- product_sizes, product_colors, product_operations,
-- product_operation_rates, production_plans, production_plan_sizes) or
-- its RLS/auth — that stays exactly as it is.

-- ---------------------------------------------------------------------------
-- 1. app_users
-- ---------------------------------------------------------------------------
create table if not exists app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

-- SECURITY DEFINER so it bypasses RLS on app_users internally — used by
-- every policy below instead of a raw "select id from app_users" subquery.
-- That raw form would re-trigger app_users' own RLS policy every time it's
-- evaluated (including from app_users' own policy), causing Postgres error
-- 42P17 "infinite recursion detected in policy for relation app_users".
create or replace function public.is_app_user()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (select 1 from app_users where id = auth.uid());
$$;

alter table app_users enable row level security;
drop policy if exists "allowed users read directory" on app_users;
create policy "allowed users read directory" on app_users
  for select using (is_app_user());

-- Resolves username -> email for the login screen, callable *before* the
-- user is authenticated (grant to anon). Returns nothing for an unknown
-- username. security definer so it can read app_users regardless of the
-- caller's own row-level access (there isn't one yet, pre-login).
create or replace function public.resolve_login_email(p_username text)
returns text
language sql
security definer
stable
set search_path = public
as $$
  select email from app_users where username = lower(trim(p_username));
$$;
grant execute on function public.resolve_login_email(text) to anon, authenticated;

-- Seed the two allowed users. Run this block only after both Supabase Auth
-- accounts already exist (arslanjamil6@gmail.com and mianaqeel125@gmail.com
-- — both confirmed to exist already).
insert into app_users (id, username, display_name, email)
select id, 'arslan', 'Arslan', email from auth.users where email = 'arslanjamil6@gmail.com'
on conflict (id) do update set username = excluded.username, display_name = excluded.display_name, email = excluded.email;

insert into app_users (id, username, display_name, email)
select id, 'aqeel', 'Aqeel', email from auth.users where email = 'mianaqeel125@gmail.com'
on conflict (id) do update set username = excluded.username, display_name = excluded.display_name, email = excluded.email;

-- Helper used by the audit trigger to resolve "who is doing this write".
create or replace function public.current_app_username()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select username from app_users where id = auth.uid();
$$;

-- ---------------------------------------------------------------------------
-- 2. audit_log — append-only, written only by the trigger below (security
--    definer), never directly by the app.
-- ---------------------------------------------------------------------------
create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  action text not null check (action in ('create', 'update', 'delete')),
  performed_by uuid,
  performed_by_username text,
  performed_at timestamptz not null default now(),
  old_data jsonb,
  new_data jsonb
);
create index if not exists idx_audit_log_table_record on audit_log(table_name, record_id);
create index if not exists idx_audit_log_performed_at on audit_log(performed_at desc);

alter table audit_log enable row level security;
drop policy if exists "allowed users read audit log" on audit_log;
create policy "allowed users read audit log" on audit_log
  for select using (is_app_user());

-- ---------------------------------------------------------------------------
-- 3. Reusable trigger: stamps created_by_*/updated_by_* on the row AND
--    writes an audit_log entry, for insert/update/delete alike.
-- ---------------------------------------------------------------------------
create or replace function public.stamp_and_log_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  uname text := current_app_username();
begin
  if tg_op = 'INSERT' then
    new.created_by_user_id := auth.uid();
    new.created_by_username := uname;
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, new_data)
      values (tg_table_name, new.id::text, 'create', auth.uid(), uname, to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_by_user_id := auth.uid();
    new.updated_by_username := uname;
    new.updated_at := now();
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, old_data, new_data)
      values (tg_table_name, new.id::text, 'update', auth.uid(), uname, to_jsonb(old), to_jsonb(new));
    return new;
  elsif tg_op = 'DELETE' then
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, old_data)
      values (tg_table_name, old.id::text, 'delete', auth.uid(), uname, to_jsonb(old));
    return old;
  end if;
  return null;
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. Per-table: add attribution columns + attach the trigger.
--    Covers every business table that can be created/edited/deleted.
--    Written as flat, explicit statements (not a PL/pgSQL loop) so that if
--    any single line fails, Supabase's SQL editor points at that exact
--    line instead of an opaque "error in PL/pgSQL function" — and so nothing
--    hides inside a DO block that could obscure a failure.
-- ---------------------------------------------------------------------------
alter table employees add column if not exists created_by_user_id uuid;
alter table employees add column if not exists created_by_username text;
alter table employees add column if not exists updated_by_user_id uuid;
alter table employees add column if not exists updated_by_username text;
alter table employees add column if not exists updated_at timestamptz;
drop trigger if exists audit_employees on employees;
create trigger audit_employees before insert or update or delete on employees for each row execute function stamp_and_log_audit();

alter table supervisors add column if not exists created_by_user_id uuid;
alter table supervisors add column if not exists created_by_username text;
alter table supervisors add column if not exists updated_by_user_id uuid;
alter table supervisors add column if not exists updated_by_username text;
alter table supervisors add column if not exists updated_at timestamptz;
drop trigger if exists audit_supervisors on supervisors;
create trigger audit_supervisors before insert or update or delete on supervisors for each row execute function stamp_and_log_audit();

alter table advances add column if not exists created_by_user_id uuid;
alter table advances add column if not exists created_by_username text;
alter table advances add column if not exists updated_by_user_id uuid;
alter table advances add column if not exists updated_by_username text;
alter table advances add column if not exists updated_at timestamptz;
drop trigger if exists audit_advances on advances;
create trigger audit_advances before insert or update or delete on advances for each row execute function stamp_and_log_audit();

alter table salary_payments add column if not exists created_by_user_id uuid;
alter table salary_payments add column if not exists created_by_username text;
alter table salary_payments add column if not exists updated_by_user_id uuid;
alter table salary_payments add column if not exists updated_by_username text;
alter table salary_payments add column if not exists updated_at timestamptz;
drop trigger if exists audit_salary_payments on salary_payments;
create trigger audit_salary_payments before insert or update or delete on salary_payments for each row execute function stamp_and_log_audit();

alter table unit_payments add column if not exists created_by_user_id uuid;
alter table unit_payments add column if not exists created_by_username text;
alter table unit_payments add column if not exists updated_by_user_id uuid;
alter table unit_payments add column if not exists updated_by_username text;
alter table unit_payments add column if not exists updated_at timestamptz;
drop trigger if exists audit_unit_payments on unit_payments;
create trigger audit_unit_payments before insert or update or delete on unit_payments for each row execute function stamp_and_log_audit();

alter table advance_deductions add column if not exists created_by_user_id uuid;
alter table advance_deductions add column if not exists created_by_username text;
alter table advance_deductions add column if not exists updated_by_user_id uuid;
alter table advance_deductions add column if not exists updated_by_username text;
alter table advance_deductions add column if not exists updated_at timestamptz;
drop trigger if exists audit_advance_deductions on advance_deductions;
create trigger audit_advance_deductions before insert or update or delete on advance_deductions for each row execute function stamp_and_log_audit();

alter table expenses add column if not exists created_by_user_id uuid;
alter table expenses add column if not exists created_by_username text;
alter table expenses add column if not exists updated_by_user_id uuid;
alter table expenses add column if not exists updated_by_username text;
alter table expenses add column if not exists updated_at timestamptz;
drop trigger if exists audit_expenses on expenses;
create trigger audit_expenses before insert or update or delete on expenses for each row execute function stamp_and_log_audit();

alter table expense_categories add column if not exists created_by_user_id uuid;
alter table expense_categories add column if not exists created_by_username text;
alter table expense_categories add column if not exists updated_by_user_id uuid;
alter table expense_categories add column if not exists updated_by_username text;
alter table expense_categories add column if not exists updated_at timestamptz;
drop trigger if exists audit_expense_categories on expense_categories;
create trigger audit_expense_categories before insert or update or delete on expense_categories for each row execute function stamp_and_log_audit();

alter table khadim_transactions add column if not exists created_by_user_id uuid;
alter table khadim_transactions add column if not exists created_by_username text;
alter table khadim_transactions add column if not exists updated_by_user_id uuid;
alter table khadim_transactions add column if not exists updated_by_username text;
alter table khadim_transactions add column if not exists updated_at timestamptz;
drop trigger if exists audit_khadim_transactions on khadim_transactions;
create trigger audit_khadim_transactions before insert or update or delete on khadim_transactions for each row execute function stamp_and_log_audit();

alter table units add column if not exists created_by_user_id uuid;
alter table units add column if not exists created_by_username text;
alter table units add column if not exists updated_by_user_id uuid;
alter table units add column if not exists updated_by_username text;
alter table units add column if not exists updated_at timestamptz;
drop trigger if exists audit_units on units;
create trigger audit_units before insert or update or delete on units for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- 5. RLS tightening — replace "allow all" with "must be an allowed user".
--    Untouched: profiles/colors/products/... (Factory module) and
--    app_users/audit_log (already policed above). Same flat-statement
--    reasoning as section 4.
-- ---------------------------------------------------------------------------
drop policy if exists "allow all" on employees;
create policy "authenticated app users only" on employees for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on supervisors;
create policy "authenticated app users only" on supervisors for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on advances;
create policy "authenticated app users only" on advances for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on expenses;
create policy "authenticated app users only" on expenses for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on salary_payments;
create policy "authenticated app users only" on salary_payments for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on unit_payments;
create policy "authenticated app users only" on unit_payments for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on advance_deductions;
create policy "authenticated app users only" on advance_deductions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on units;
create policy "authenticated app users only" on units for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on khadim_transactions;
create policy "authenticated app users only" on khadim_transactions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on expense_categories;
create policy "authenticated app users only" on expense_categories for all using (is_app_user()) with check (is_app_user());
