-- Protees Business Manager — full schema
-- Two business units:
--   Protees Unit        — one supervisor, bi-weekly payments, unit expenses
--   Cutting Department   — employees, monthly salary + overtime + advances
-- No employee_id-style foreign keys for people — names (text) are the join
-- key everywhere, matching how this app's data is actually keyed. Safe to
-- run on a fresh database or on top of the existing tables — every
-- statement is idempotent.

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  salary numeric(12,2) not null default 0,
  join_date date,
  created_at timestamptz not null default now()
);
alter table employees add column if not exists join_date date;

create table if not exists supervisors (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Advances — shared by both departments, disambiguated by `department`.
-- ---------------------------------------------------------------------------
create table if not exists advances (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  department text not null default 'cutting_department',
  amount numeric(12,2) not null check (amount > 0),
  payment_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table advances add column if not exists department text not null default 'cutting_department';
alter table advances add column if not exists notes text;
alter table advances drop constraint if exists advances_department_check;
alter table advances add constraint advances_department_check
  check (department in ('cutting_department', 'protees_unit'));

-- ---------------------------------------------------------------------------
-- Unit Expenses (Protees Unit) — table name stays `expenses` for continuity.
-- ---------------------------------------------------------------------------
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'Other Expenses',
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table expenses add column if not exists category text not null default 'Other Expenses';
alter table expenses add column if not exists notes text;
-- Categories are database-driven (see expense_categories below) — no fixed
-- check constraint on this column.
alter table expenses drop constraint if exists expenses_category_check;

-- ---------------------------------------------------------------------------
-- Expense categories — database-driven, so new categories added from the
-- app (via "+ Add New Category") need no code changes.
-- ---------------------------------------------------------------------------
create table if not exists expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
insert into expense_categories (name) values
  ('Thread'),
  ('Fabric'),
  ('Packing'),
  ('Transport'),
  ('Printing'),
  ('Khadim Hussain'),
  ('Food Grocery'),
  ('Food Vegetable'),
  ('Rotiyan'),
  ('Gas'),
  ('Diesel'),
  ('Transportation'),
  ('Other Expenses')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Khadim Hussain Account — a running ledger of money given to Khadim
-- Hussain for unit material purchases (Payment Given) vs. bills he submits
-- against it (Bill Submitted). Balance = payments given - bills submitted.
-- ---------------------------------------------------------------------------
create table if not exists khadim_transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('payment_given', 'bill_submitted')),
  date date not null default current_date,
  amount numeric(12,2) not null check (amount > 0),
  notes text,
  description text,
  created_at timestamptz not null default now()
);
create index if not exists idx_khadim_transactions_date on khadim_transactions(date);

-- ---------------------------------------------------------------------------
-- Salary payments — Cutting Department, monthly.
-- Net = base + overtime - deduction (computed by the app on insert).
-- ---------------------------------------------------------------------------
create table if not exists salary_payments (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  base_amount numeric(12,2) not null,
  overtime_amount numeric(12,2) not null default 0,
  deduction_amount numeric(12,2) not null default 0,
  net_amount numeric(12,2) not null,
  month int not null check (month between 1 and 12),
  year int not null,
  payment_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);
alter table salary_payments add column if not exists overtime_amount numeric(12,2) not null default 0;

-- ---------------------------------------------------------------------------
-- Unit payments — Protees Unit, bi-weekly.
-- Net = total - advance given (computed by the app on insert).
-- ---------------------------------------------------------------------------
create table if not exists unit_payments (
  id bigint generated by default as identity primary key,
  supervisor_name text not null,
  payment_date date not null default current_date,
  period_start date not null,
  period_end date not null,
  total_amount numeric(12,2) not null default 0,
  overtime_amount numeric(12,2) not null default 0,
  advance_given numeric(12,2) not null default 0,
  net_amount numeric(12,2) not null default 0,
  unit_expenses_during_period numeric(12,2) not null default 0,
  notes text,
  month int not null,
  year int not null,
  created_at timestamptz not null default now()
);
alter table unit_payments add column if not exists overtime_amount numeric(12,2) not null default 0;

-- ---------------------------------------------------------------------------
-- Advance deductions — links a payment (salary OR unit) back to the
-- advance(s) it paid down. Exactly one of salary_payment_id / unit_payment_id
-- is set per row.
-- ---------------------------------------------------------------------------
create table if not exists advance_deductions (
  id bigint generated by default as identity primary key,
  advance_id bigint references advances(id) on delete set null,
  employee_name text not null,
  department text not null default 'cutting_department',
  salary_payment_id bigint references salary_payments(id) on delete cascade,
  unit_payment_id bigint references unit_payments(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  created_at timestamptz not null default now()
);
alter table advance_deductions add column if not exists department text not null default 'cutting_department';
alter table advance_deductions add column if not exists unit_payment_id bigint references unit_payments(id) on delete cascade;

-- ---------------------------------------------------------------------------
-- Units — legacy branch/location registry (kept for continuity; the Protees
-- Unit module above is now the primary way this business is modeled).
-- ---------------------------------------------------------------------------
create table if not exists units (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  created_at timestamptz not null default now()
);

create index if not exists idx_advances_employee_name on advances(employee_name);
create index if not exists idx_advances_department on advances(department);
create index if not exists idx_salary_payments_employee_name on salary_payments(employee_name);
create index if not exists idx_advance_deductions_employee_name on advance_deductions(employee_name);
create index if not exists idx_advance_deductions_department on advance_deductions(department);
create index if not exists idx_unit_payments_supervisor_name on unit_payments(supervisor_name);
create index if not exists idx_unit_payments_period on unit_payments(period_start, period_end);

-- ---------------------------------------------------------------------------
-- View: outstanding advance balance per (name, department)
-- ---------------------------------------------------------------------------
create or replace view advance_balance_by_name as
select
  coalesce(adv.employee_name, ded.employee_name) as name,
  coalesce(adv.department, ded.department) as department,
  coalesce(adv.total_advanced, 0) as total_advanced,
  coalesce(ded.total_deducted, 0) as total_deducted,
  coalesce(adv.total_advanced, 0) - coalesce(ded.total_deducted, 0) as balance
from (
  select employee_name, department, sum(amount) as total_advanced
  from advances
  group by employee_name, department
) adv
full outer join (
  select employee_name, department, sum(amount) as total_deducted
  from advance_deductions
  group by employee_name, department
) ded on ded.employee_name = adv.employee_name and ded.department = adv.department;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- This app is a single-tenant internal tool used with the Supabase publishable
-- (anon) key. These policies allow full read/write access. Replace with
-- auth-scoped policies before exposing this publicly.
-- ---------------------------------------------------------------------------
alter table employees enable row level security;
alter table supervisors enable row level security;
alter table advances enable row level security;
alter table expenses enable row level security;
alter table salary_payments enable row level security;
alter table unit_payments enable row level security;
alter table advance_deductions enable row level security;
alter table units enable row level security;
alter table khadim_transactions enable row level security;
alter table expense_categories enable row level security;

drop policy if exists "allow all" on employees;
drop policy if exists "allow all" on supervisors;
drop policy if exists "allow all" on advances;
drop policy if exists "allow all" on expenses;
drop policy if exists "allow all" on salary_payments;
drop policy if exists "allow all" on unit_payments;
drop policy if exists "allow all" on advance_deductions;
drop policy if exists "allow all" on units;
drop policy if exists "allow all" on khadim_transactions;
drop policy if exists "allow all" on expense_categories;

create policy "allow all" on employees for all using (true) with check (true);
create policy "allow all" on supervisors for all using (true) with check (true);
create policy "allow all" on advances for all using (true) with check (true);
create policy "allow all" on expenses for all using (true) with check (true);
create policy "allow all" on salary_payments for all using (true) with check (true);
create policy "allow all" on unit_payments for all using (true) with check (true);
create policy "allow all" on advance_deductions for all using (true) with check (true);
create policy "allow all" on units for all using (true) with check (true);
create policy "allow all" on khadim_transactions for all using (true) with check (true);
create policy "allow all" on expense_categories for all using (true) with check (true);

-- =============================================================================
-- FACTORY / UNIT PRODUCTION MODULE (Phase 1) — appended from migration_006
-- =============================================================================

-- Protees Business Manager — Factory / Unit Production module, Phase 1
-- Adds: Factory-only authentication (profiles + role), Product setup
-- (sizes/colors/operations/rate history), and Production Plans.
--
-- IMPORTANT — scope of auth: this ONLY gates the new /factory/* routes.
-- Every existing table (employees, advances, expenses, salary_payments,
-- unit_payments, etc.) is untouched and keeps its current "allow all"
-- policies exactly as-is. This migration adds new tables only — nothing
-- existing is altered, dropped, or renamed. Safe to re-run.

-- ---------------------------------------------------------------------------
-- Factory user profiles — one row per Supabase Auth user, added by a
-- trigger the moment they sign up. `role` starts NULL ("pending approval")
-- until an admin assigns one from the Team Members screen.
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text check (role in ('admin', 'cutting_head', 'stitching_head', 'quality_head', 'store_manager')),
  created_at timestamptz not null default now()
);

create or replace function public.factory_role()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role from profiles where id = auth.uid();
$$;

create or replace function public.handle_new_factory_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email), null)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_factory_user();

alter table profiles enable row level security;
drop policy if exists "read own or admin reads all" on profiles;
drop policy if exists "admin writes all" on profiles;
create policy "read own or admin reads all" on profiles
  for select using (auth.uid() = id or factory_role() = 'admin');
create policy "admin writes all" on profiles
  for update using (factory_role() = 'admin') with check (factory_role() = 'admin');

-- ---------------------------------------------------------------------------
-- Global color catalog — admin-extendable, shared across products.
-- ---------------------------------------------------------------------------
create table if not exists colors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  hex text not null default '#64748b',
  created_at timestamptz not null default now()
);
insert into colors (name, hex) values
  ('Black', '#0f172a'),
  ('White', '#f8fafc'),
  ('Red', '#ef4444'),
  ('Blue', '#3b82f6'),
  ('Navy', '#1e3a8a'),
  ('Grey', '#6b7280')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Products — admin-configured. `production_type` decides whether a plan
-- for this product routes through Digital Print before Cutting.
-- ---------------------------------------------------------------------------
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  picture_url text,
  production_type text not null default 'normal' check (production_type in ('normal', 'digital_print')),
  size_group text not null default 'adult' check (size_group in ('adult', 'kids')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  size_label text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (product_id, size_label)
);

create table if not exists product_colors (
  product_id bigint not null references products(id) on delete cascade,
  color_id bigint not null references colors(id) on delete cascade,
  primary key (product_id, color_id)
);

-- Operations are grouped under a free-text department label (Overlock,
-- Flat Lock, Singer, Clipping, ...) chosen per product by Admin — never a
-- fixed list, since different products need entirely different operations.
create table if not exists product_operations (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  department_label text not null,
  operation_name text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Rate history: a rate is NEVER updated in place. Changing a rate inserts a
-- new row with effective_from = now(); the "current" rate is the latest row
-- per operation. Historical production always snapshots the rate that was
-- current at completion time, so old records never move.
create table if not exists product_operation_rates (
  id bigint generated by default as identity primary key,
  product_operation_id bigint not null references product_operations(id) on delete cascade,
  rate numeric(12,2) not null check (rate >= 0),
  effective_from timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists idx_product_operation_rates_op on product_operation_rates(product_operation_id, effective_from desc);

create or replace view product_operation_current_rates as
select distinct on (product_operation_id)
  product_operation_id,
  rate,
  effective_from
from product_operation_rates
order by product_operation_id, effective_from desc;

-- ---------------------------------------------------------------------------
-- Production Plans — Admin creates. Only relevant (configured) sizes for
-- the chosen product should be offered by the UI.
-- ---------------------------------------------------------------------------
create table if not exists production_plans (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id),
  color_id bigint references colors(id),
  production_type text not null default 'normal' check (production_type in ('normal', 'digital_print')),
  plan_date date not null default current_date,
  expected_completion_date date,
  remarks text,
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'completed', 'cancelled')),
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists production_plan_sizes (
  id bigint generated by default as identity primary key,
  production_plan_id bigint not null references production_plans(id) on delete cascade,
  size_label text not null,
  planned_qty int not null check (planned_qty >= 0),
  unique (production_plan_id, size_label)
);

create index if not exists idx_production_plans_status on production_plans(status);
create index if not exists idx_production_plan_sizes_plan on production_plan_sizes(production_plan_id);

-- ---------------------------------------------------------------------------
-- Row Level Security — factory tables only. Any signed-in user with an
-- approved role (profiles.role is not null) can read; only admin can write
-- product/operation/rate/plan configuration, matching "workers never touch
-- rates" at the database level, not just in the UI.
-- ---------------------------------------------------------------------------
alter table colors enable row level security;
alter table products enable row level security;
alter table product_sizes enable row level security;
alter table product_colors enable row level security;
alter table product_operations enable row level security;
alter table product_operation_rates enable row level security;
alter table production_plans enable row level security;
alter table production_plan_sizes enable row level security;

drop policy if exists "factory read" on colors;
drop policy if exists "admin write" on colors;
create policy "factory read" on colors for select using (factory_role() is not null);
create policy "admin write" on colors for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on products;
drop policy if exists "admin write" on products;
create policy "factory read" on products for select using (factory_role() is not null);
create policy "admin write" on products for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_sizes;
drop policy if exists "admin write" on product_sizes;
create policy "factory read" on product_sizes for select using (factory_role() is not null);
create policy "admin write" on product_sizes for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_colors;
drop policy if exists "admin write" on product_colors;
create policy "factory read" on product_colors for select using (factory_role() is not null);
create policy "admin write" on product_colors for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_operations;
drop policy if exists "admin write" on product_operations;
create policy "factory read" on product_operations for select using (factory_role() is not null);
create policy "admin write" on product_operations for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on product_operation_rates;
drop policy if exists "admin write" on product_operation_rates;
create policy "factory read" on product_operation_rates for select using (factory_role() is not null);
create policy "admin write" on product_operation_rates for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on production_plans;
drop policy if exists "admin write" on production_plans;
create policy "factory read" on production_plans for select using (factory_role() is not null);
create policy "admin write" on production_plans for all using (factory_role() = 'admin') with check (factory_role() = 'admin');

drop policy if exists "factory read" on production_plan_sizes;
drop policy if exists "admin write" on production_plan_sizes;
create policy "factory read" on production_plan_sizes for select using (factory_role() is not null);
create policy "admin write" on production_plan_sizes for all using (factory_role() = 'admin') with check (factory_role() = 'admin');


-- =============================================================================
-- Main-app authentication + audit trail (see migration_007_auth_and_audit.sql)
-- =============================================================================

-- Protees Business Manager — main-app authentication + full audit trail
--
-- Adds:
--   1. app_users: maps a fixed username (aqeel/arslan) to a Supabase Auth
--      account, so the main app can offer username-based login while
--      Supabase Auth itself still authenticates by email under the hood.
--   2. audit_log: an append-only record of every create/update/delete
--      across the business tables, including a full snapshot of deleted
--      rows (which otherwise vanish with no trace).
--   3. created_by_user_id / created_by_username / updated_by_user_id /
--      updated_by_username / updated_at columns on every business table,
--      auto-stamped by a trigger — no frontend code has to set these.
--   4. RLS on the business tables tightened from "allow all" to
--      "must be a row in app_users" — closing the anon-key-can-write-
--      anything gap now that the app has real logins.
--
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / OR
-- REPLACE / DROP POLICY IF EXISTS). Existing rows are untouched — the new
-- columns come in NULL for pre-existing records, which is expected (see
-- migration notes shared with the user).
--
-- Does NOT touch: the Factory module (profiles, colors, products,
-- product_sizes, product_colors, product_operations,
-- product_operation_rates, production_plans, production_plan_sizes) or
-- its RLS/auth — that stays exactly as it is.

-- ---------------------------------------------------------------------------
-- 1. app_users
-- ---------------------------------------------------------------------------
create table if not exists app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

-- SECURITY DEFINER so it bypasses RLS on app_users internally — used by
-- every policy below instead of a raw "select id from app_users" subquery.
-- That raw form would re-trigger app_users' own RLS policy every time it's
-- evaluated (including from app_users' own policy), causing Postgres error
-- 42P17 "infinite recursion detected in policy for relation app_users".
create or replace function public.is_app_user()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (select 1 from app_users where id = auth.uid());
$$;

alter table app_users enable row level security;
drop policy if exists "allowed users read directory" on app_users;
create policy "allowed users read directory" on app_users
  for select using (is_app_user());

-- Resolves username -> email for the login screen, callable *before* the
-- user is authenticated (grant to anon). Returns nothing for an unknown
-- username. security definer so it can read app_users regardless of the
-- caller's own row-level access (there isn't one yet, pre-login).
create or replace function public.resolve_login_email(p_username text)
returns text
language sql
security definer
stable
set search_path = public
as $$
  select email from app_users where username = lower(trim(p_username));
$$;
grant execute on function public.resolve_login_email(text) to anon, authenticated;

-- Seed the two allowed users. Run this block only after both Supabase Auth
-- accounts already exist (arslanjamil6@gmail.com and mianaqeel125@gmail.com
-- — both confirmed to exist already).
insert into app_users (id, username, display_name, email)
select id, 'arslan', 'Arslan', email from auth.users where email = 'arslanjamil6@gmail.com'
on conflict (id) do update set username = excluded.username, display_name = excluded.display_name, email = excluded.email;

insert into app_users (id, username, display_name, email)
select id, 'aqeel', 'Aqeel', email from auth.users where email = 'mianaqeel125@gmail.com'
on conflict (id) do update set username = excluded.username, display_name = excluded.display_name, email = excluded.email;

-- Helper used by the audit trigger to resolve "who is doing this write".
create or replace function public.current_app_username()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select username from app_users where id = auth.uid();
$$;

-- ---------------------------------------------------------------------------
-- 2. audit_log — append-only, written only by the trigger below (security
--    definer), never directly by the app.
-- ---------------------------------------------------------------------------
create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  action text not null check (action in ('create', 'update', 'delete')),
  performed_by uuid,
  performed_by_username text,
  performed_at timestamptz not null default now(),
  old_data jsonb,
  new_data jsonb
);
create index if not exists idx_audit_log_table_record on audit_log(table_name, record_id);
create index if not exists idx_audit_log_performed_at on audit_log(performed_at desc);

alter table audit_log enable row level security;
drop policy if exists "allowed users read audit log" on audit_log;
create policy "allowed users read audit log" on audit_log
  for select using (is_app_user());

-- ---------------------------------------------------------------------------
-- 3. Reusable trigger: stamps created_by_*/updated_by_* on the row AND
--    writes an audit_log entry, for insert/update/delete alike.
-- ---------------------------------------------------------------------------
create or replace function public.stamp_and_log_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  uname text := current_app_username();
begin
  if tg_op = 'INSERT' then
    new.created_by_user_id := auth.uid();
    new.created_by_username := uname;
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, new_data)
      values (tg_table_name, new.id::text, 'create', auth.uid(), uname, to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_by_user_id := auth.uid();
    new.updated_by_username := uname;
    new.updated_at := now();
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, old_data, new_data)
      values (tg_table_name, new.id::text, 'update', auth.uid(), uname, to_jsonb(old), to_jsonb(new));
    return new;
  elsif tg_op = 'DELETE' then
    insert into audit_log (table_name, record_id, action, performed_by, performed_by_username, old_data)
      values (tg_table_name, old.id::text, 'delete', auth.uid(), uname, to_jsonb(old));
    return old;
  end if;
  return null;
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. Per-table: add attribution columns + attach the trigger.
--    Covers every business table that can be created/edited/deleted.
--    Written as flat, explicit statements (not a PL/pgSQL loop) so that if
--    any single line fails, Supabase's SQL editor points at that exact
--    line instead of an opaque "error in PL/pgSQL function" — and so nothing
--    hides inside a DO block that could obscure a failure.
-- ---------------------------------------------------------------------------
alter table employees add column if not exists created_by_user_id uuid;
alter table employees add column if not exists created_by_username text;
alter table employees add column if not exists updated_by_user_id uuid;
alter table employees add column if not exists updated_by_username text;
alter table employees add column if not exists updated_at timestamptz;
drop trigger if exists audit_employees on employees;
create trigger audit_employees before insert or update or delete on employees for each row execute function stamp_and_log_audit();

alter table supervisors add column if not exists created_by_user_id uuid;
alter table supervisors add column if not exists created_by_username text;
alter table supervisors add column if not exists updated_by_user_id uuid;
alter table supervisors add column if not exists updated_by_username text;
alter table supervisors add column if not exists updated_at timestamptz;
drop trigger if exists audit_supervisors on supervisors;
create trigger audit_supervisors before insert or update or delete on supervisors for each row execute function stamp_and_log_audit();

alter table advances add column if not exists created_by_user_id uuid;
alter table advances add column if not exists created_by_username text;
alter table advances add column if not exists updated_by_user_id uuid;
alter table advances add column if not exists updated_by_username text;
alter table advances add column if not exists updated_at timestamptz;
drop trigger if exists audit_advances on advances;
create trigger audit_advances before insert or update or delete on advances for each row execute function stamp_and_log_audit();

alter table salary_payments add column if not exists created_by_user_id uuid;
alter table salary_payments add column if not exists created_by_username text;
alter table salary_payments add column if not exists updated_by_user_id uuid;
alter table salary_payments add column if not exists updated_by_username text;
alter table salary_payments add column if not exists updated_at timestamptz;
drop trigger if exists audit_salary_payments on salary_payments;
create trigger audit_salary_payments before insert or update or delete on salary_payments for each row execute function stamp_and_log_audit();

alter table unit_payments add column if not exists created_by_user_id uuid;
alter table unit_payments add column if not exists created_by_username text;
alter table unit_payments add column if not exists updated_by_user_id uuid;
alter table unit_payments add column if not exists updated_by_username text;
alter table unit_payments add column if not exists updated_at timestamptz;
drop trigger if exists audit_unit_payments on unit_payments;
create trigger audit_unit_payments before insert or update or delete on unit_payments for each row execute function stamp_and_log_audit();

alter table advance_deductions add column if not exists created_by_user_id uuid;
alter table advance_deductions add column if not exists created_by_username text;
alter table advance_deductions add column if not exists updated_by_user_id uuid;
alter table advance_deductions add column if not exists updated_by_username text;
alter table advance_deductions add column if not exists updated_at timestamptz;
drop trigger if exists audit_advance_deductions on advance_deductions;
create trigger audit_advance_deductions before insert or update or delete on advance_deductions for each row execute function stamp_and_log_audit();

alter table expenses add column if not exists created_by_user_id uuid;
alter table expenses add column if not exists created_by_username text;
alter table expenses add column if not exists updated_by_user_id uuid;
alter table expenses add column if not exists updated_by_username text;
alter table expenses add column if not exists updated_at timestamptz;
drop trigger if exists audit_expenses on expenses;
create trigger audit_expenses before insert or update or delete on expenses for each row execute function stamp_and_log_audit();

alter table expense_categories add column if not exists created_by_user_id uuid;
alter table expense_categories add column if not exists created_by_username text;
alter table expense_categories add column if not exists updated_by_user_id uuid;
alter table expense_categories add column if not exists updated_by_username text;
alter table expense_categories add column if not exists updated_at timestamptz;
drop trigger if exists audit_expense_categories on expense_categories;
create trigger audit_expense_categories before insert or update or delete on expense_categories for each row execute function stamp_and_log_audit();

alter table khadim_transactions add column if not exists created_by_user_id uuid;
alter table khadim_transactions add column if not exists created_by_username text;
alter table khadim_transactions add column if not exists updated_by_user_id uuid;
alter table khadim_transactions add column if not exists updated_by_username text;
alter table khadim_transactions add column if not exists updated_at timestamptz;
drop trigger if exists audit_khadim_transactions on khadim_transactions;
create trigger audit_khadim_transactions before insert or update or delete on khadim_transactions for each row execute function stamp_and_log_audit();

alter table units add column if not exists created_by_user_id uuid;
alter table units add column if not exists created_by_username text;
alter table units add column if not exists updated_by_user_id uuid;
alter table units add column if not exists updated_by_username text;
alter table units add column if not exists updated_at timestamptz;
drop trigger if exists audit_units on units;
create trigger audit_units before insert or update or delete on units for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- 5. RLS tightening — replace "allow all" with "must be an allowed user".
--    Untouched: profiles/colors/products/... (Factory module) and
--    app_users/audit_log (already policed above). Same flat-statement
--    reasoning as section 4.
-- ---------------------------------------------------------------------------
drop policy if exists "allow all" on employees;
create policy "authenticated app users only" on employees for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on supervisors;
create policy "authenticated app users only" on supervisors for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on advances;
create policy "authenticated app users only" on advances for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on expenses;
create policy "authenticated app users only" on expenses for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on salary_payments;
create policy "authenticated app users only" on salary_payments for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on unit_payments;
create policy "authenticated app users only" on unit_payments for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on advance_deductions;
create policy "authenticated app users only" on advance_deductions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on units;
create policy "authenticated app users only" on units for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on khadim_transactions;
create policy "authenticated app users only" on khadim_transactions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "allow all" on expense_categories;
create policy "authenticated app users only" on expense_categories for all using (is_app_user()) with check (is_app_user());

-- =============================================================================
-- Contract / Piece-Rate employees (see migration_008_contract_employees.sql)
-- =============================================================================

-- Protees Business Manager — Contract / Piece-Rate employee type
--
-- Adds:
--   1. employees.employee_type ('monthly' | 'contract'), defaulting existing
--      rows to 'monthly' so current behavior is unchanged for everyone.
--   2. employees.rate_per_piece — only meaningful for contract employees.
--   3. salary_payments.pieces_completed / rate_per_piece — a snapshot of the
--      calculation inputs at payment time, so a later rate change never
--      alters historical payments (same "snapshot, don't recompute"
--      approach already used elsewhere in this schema).
--
-- Existing "monthly" flow (manual salary entry) is completely unchanged.
-- Audit trail needs no changes — the existing stamp_and_log_audit()
-- trigger on employees/salary_payments already captures every column via
-- to_jsonb(new)/to_jsonb(old), so these new columns are automatically
-- included in created/updated audit log entries.
--
-- Safe to re-run.

alter table employees add column if not exists employee_type text not null default 'monthly';
alter table employees drop constraint if exists employees_employee_type_check;
alter table employees add constraint employees_employee_type_check
  check (employee_type in ('monthly', 'contract'));

alter table employees add column if not exists rate_per_piece numeric(12,2);

alter table salary_payments add column if not exists pieces_completed int;
alter table salary_payments add column if not exists rate_per_piece numeric(12,2);

-- =============================================================================
-- Dashboard widget layout persistence (see migration_009_dashboard_layout.sql)
-- =============================================================================

-- Protees Business Manager — Dashboard widget layout persistence
--
-- Adds a single small table so each app user's drag-and-drop dashboard
-- widget order survives a page refresh (and follows them between devices,
-- since it's keyed by their app_users row, not the browser).
--
-- One row per user, upserted from the client whenever they reorder a
-- widget. Not part of the audit trail (stamp_and_log_audit) — this is a
-- personal UI preference, not a business record.
--
-- Safe to re-run.

create table if not exists dashboard_layouts (
  user_id uuid primary key references app_users(id) on delete cascade,
  widget_order text[] not null,
  updated_at timestamptz not null default now()
);

alter table dashboard_layouts enable row level security;

drop policy if exists "users manage their own dashboard layout" on dashboard_layouts;
create policy "users manage their own dashboard layout" on dashboard_layouts
  for all using (is_app_user() and user_id = auth.uid())
  with check (is_app_user() and user_id = auth.uid());

-- =============================================================================
-- Unit module restructure + Zakat tracking (see migration_010_unit_zakat.sql)
-- =============================================================================

-- Protees Business Manager — Unit module restructure + Zakat tracking
--
-- Adds:
--   1. employees.employee_group ('regular' | 'unit') — Unit Employees'
--      salaries are excluded from Regular Payroll totals/reports and
--      counted toward Unit Payroll instead. Existing rows default to
--      'regular', so current behavior is unchanged for everyone.
--   2. expenses.expense_scope ('business' | 'unit') — Unit Expenses are
--      excluded from normal Business Expense totals and included in Unit
--      reports/dashboard calculations instead. Existing rows default to
--      'business' (unchanged behavior).
--   3. zakat_transactions — full history of Zakat distributions (recipient,
--      amount, date, notes), audited like every other business table.
--   4. zakat_settings — a single-row settings table holding the editable
--      monthly Zakat budget (defaults to Rs 100,000 per spec).
--
-- Does NOT touch: units, supervisors, unit_payments, advances (Give
-- Advance / Make Payment flow stays exactly as it is) or the Factory
-- module. No quantity/production tracking added anywhere.
--
-- Safe to re-run.

alter table employees add column if not exists employee_group text not null default 'regular';
alter table employees drop constraint if exists employees_employee_group_check;
alter table employees add constraint employees_employee_group_check
  check (employee_group in ('regular', 'unit'));

alter table expenses add column if not exists expense_scope text not null default 'business';
alter table expenses drop constraint if exists expenses_expense_scope_check;
alter table expenses add constraint expenses_expense_scope_check
  check (expense_scope in ('business', 'unit'));

create table if not exists zakat_transactions (
  id bigint generated by default as identity primary key,
  recipient_name text not null,
  amount numeric(12,2) not null,
  date date not null default current_date,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_zakat_transactions_date on zakat_transactions(date);

alter table zakat_transactions enable row level security;
drop policy if exists "authenticated app users only" on zakat_transactions;
create policy "authenticated app users only" on zakat_transactions for all using (is_app_user()) with check (is_app_user());

drop trigger if exists audit_zakat_transactions on zakat_transactions;
create trigger audit_zakat_transactions before insert or update or delete on zakat_transactions for each row execute function stamp_and_log_audit();

create table if not exists zakat_settings (
  id int primary key default 1,
  monthly_budget numeric(12,2) not null default 100000,
  updated_at timestamptz not null default now(),
  constraint zakat_settings_singleton check (id = 1)
);
insert into zakat_settings (id, monthly_budget) values (1, 100000) on conflict (id) do nothing;

alter table zakat_settings enable row level security;
drop policy if exists "authenticated app users only" on zakat_settings;
create policy "authenticated app users only" on zakat_settings for all using (is_app_user()) with check (is_app_user());

-- =============================================================================
-- Zakat opening balance + cumulative outstanding (see migration_011_zakat_opening_balance.sql)
-- =============================================================================

-- Reworks Zakat tracking from a per-month-reset budget into a running
-- outstanding balance:
--
--   Outstanding Balance = Opening Balance
--                        + (months elapsed since opening_month × Monthly Target)
--                        - (Zakat distributed since opening_month)
--
-- opening_balance: pending unpaid Zakat carried in from before tracking
-- started. opening_month: the first-of-month date it's effective as of —
-- Monthly Target accrues once per calendar month from there on, computed
-- in the app as a pure function of today's date (no cron/trigger needed).
--
-- Safe to re-run — the UPDATE only seeds these on first run.

alter table zakat_settings add column if not exists opening_balance numeric(12,2) not null default 0;
alter table zakat_settings add column if not exists opening_month date not null default date_trunc('month', current_date)::date;

update zakat_settings
set opening_balance = 326500,
    opening_month = date_trunc('month', current_date)::date,
    updated_at = now()
where id = 1 and opening_balance = 0;

-- =============================================================================
-- Collections: Shopify orders, Courier Accounts Receivable, Bank Accounts,
-- Office Cash Management (see migration_012_collections_courier_bank_cash.sql)
-- =============================================================================

-- Protees Business Manager — Collections module: Shopify orders, Courier
-- Accounts Receivable, Bank Accounts, and Office Cash Management.
--
-- New tables, all additive and RLS-protected with the existing
-- is_app_user() helper (same pattern as every other business table) —
-- except shopify_orders, which is read-only from the client (only a
-- future server-side sync, using the service-role key, ever writes to
-- it — the app itself never inserts/updates/deletes there).
--
-- Courier Accounts is a real Accounts Receivable model:
--   Pending Balance (per courier) = Total Expected Collections
--                                 - Total Payments Received
-- "Expected Collection" is recorded manually when a COD shipment goes
-- out (courier_expected_collections); "Payments Received" is recorded
-- when the courier actually remits money (courier_payments). Recording
-- a payment does not touch the expected side — the balance simply falls
-- out of the subtraction, so it can never drift.
--
-- Bank balances and the Office Cash balance are both derived the same
-- way, from append-only ledgers (bank_transactions, cash_transactions)
-- rather than a stored running total — the same "ledger, not balance
-- column" convention already used by advance_deductions elsewhere in
-- this schema.
--
-- Safe to re-run.

-- ---------------------------------------------------------------------------
-- Couriers
-- ---------------------------------------------------------------------------
create table if not exists couriers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);

-- ---------------------------------------------------------------------------
-- Courier expected collections — the "receivable" side. Recorded when a
-- COD shipment is handed to a courier.
-- ---------------------------------------------------------------------------
create table if not exists courier_expected_collections (
  id bigint generated by default as identity primary key,
  courier_id bigint not null references couriers(id),
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  order_reference text,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_courier_expected_courier on courier_expected_collections(courier_id);

-- ---------------------------------------------------------------------------
-- Bank accounts — seeded with Meezan Bank and Bank Alfalah, extensible.
-- Note: "Cash" is NOT a bank account — it's tracked by cash_transactions.
-- ---------------------------------------------------------------------------
create table if not exists bank_accounts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
insert into bank_accounts (name) values ('Meezan Bank'), ('Bank Alfalah') on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Courier payments — the "received" side. Recording one here
-- automatically inserts a matching bank_transactions credit (if bank
-- transfer) or cash_transactions cash_in (if cash) — done atomically by
-- the app in one write, not by a database trigger, so the app can show
-- the exact combined result immediately.
-- ---------------------------------------------------------------------------
create table if not exists courier_payments (
  id bigint generated by default as identity primary key,
  courier_id bigint not null references couriers(id),
  amount numeric(12,2) not null check (amount > 0),
  payment_date date not null default current_date,
  payment_type text not null check (payment_type in ('cash', 'bank_transfer')),
  bank_account_id bigint references bank_accounts(id),
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz,
  constraint courier_payments_bank_required check (
    (payment_type = 'bank_transfer' and bank_account_id is not null) or
    (payment_type = 'cash' and bank_account_id is null)
  )
);
create index if not exists idx_courier_payments_courier on courier_payments(courier_id);

-- ---------------------------------------------------------------------------
-- Bank ledger — append-only. A bank's balance = sum(credit) - sum(debit).
-- ---------------------------------------------------------------------------
create table if not exists bank_transactions (
  id bigint generated by default as identity primary key,
  bank_account_id bigint not null references bank_accounts(id),
  type text not null check (type in ('credit', 'debit')),
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  reference_type text check (reference_type in ('courier_payment', 'cash_withdrawal', 'manual')),
  reference_id bigint,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text
);
create index if not exists idx_bank_transactions_bank on bank_transactions(bank_account_id);

-- ---------------------------------------------------------------------------
-- Cash ledger — append-only. Office Cash balance = opening_balance (see
-- cash_settings) + sum(cash_in) - sum(cash_out).
-- ---------------------------------------------------------------------------
create table if not exists cash_transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('cash_in', 'cash_out')),
  category text not null,
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  reference_type text check (reference_type in ('courier_payment', 'bank_withdrawal', 'expense', 'other')),
  reference_id bigint,
  bank_account_id bigint references bank_accounts(id),
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text
);
create index if not exists idx_cash_transactions_date on cash_transactions(date);

-- ---------------------------------------------------------------------------
-- Cash opening balance — singleton row, same pattern as zakat_settings.
-- ---------------------------------------------------------------------------
create table if not exists cash_settings (
  id int primary key default 1,
  opening_balance numeric(12,2) not null default 0,
  opening_date date not null default current_date,
  updated_at timestamptz not null default now(),
  constraint cash_settings_singleton check (id = 1)
);
insert into cash_settings (id) values (1) on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Shopify orders — populated ONLY by a future server-side sync (Vercel
-- function using the Supabase service-role key, which bypasses RLS). The
-- app itself never writes here — the RLS policy below only grants SELECT.
-- ---------------------------------------------------------------------------
create table if not exists shopify_orders (
  id bigint generated by default as identity primary key,
  shopify_order_id text not null unique,
  shopify_transaction_id text,
  order_number text not null,
  order_date timestamptz not null,
  customer_name text,
  total_amount numeric(12,2) not null,
  payment_method text,
  financial_status text not null,
  imported_at timestamptz not null default now()
);
create index if not exists idx_shopify_orders_date on shopify_orders(order_date);

-- Non-secret settings only — the Admin API token is a server-only env
-- var and is never stored in the database.
create table if not exists shopify_settings (
  id int primary key default 1,
  store_domain text,
  last_synced_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint shopify_settings_singleton check (id = 1)
);
insert into shopify_settings (id) values (1) on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Audit trail — reuse the existing stamp_and_log_audit() trigger (defined
-- in migration_007) on every editable table. Ledgers (bank_transactions,
-- cash_transactions) are append-only — created_by only, no update path in
-- the app, same convention as advance_deductions.
-- ---------------------------------------------------------------------------
drop trigger if exists audit_couriers on couriers;
create trigger audit_couriers before insert or update or delete on couriers for each row execute function stamp_and_log_audit();

drop trigger if exists audit_courier_expected_collections on courier_expected_collections;
create trigger audit_courier_expected_collections before insert or update or delete on courier_expected_collections for each row execute function stamp_and_log_audit();

drop trigger if exists audit_bank_accounts on bank_accounts;
create trigger audit_bank_accounts before insert or update or delete on bank_accounts for each row execute function stamp_and_log_audit();

drop trigger if exists audit_courier_payments on courier_payments;
create trigger audit_courier_payments before insert or update or delete on courier_payments for each row execute function stamp_and_log_audit();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table couriers enable row level security;
alter table courier_expected_collections enable row level security;
alter table bank_accounts enable row level security;
alter table courier_payments enable row level security;
alter table bank_transactions enable row level security;
alter table cash_transactions enable row level security;
alter table cash_settings enable row level security;
alter table shopify_orders enable row level security;
alter table shopify_settings enable row level security;

drop policy if exists "authenticated app users only" on couriers;
create policy "authenticated app users only" on couriers for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on courier_expected_collections;
create policy "authenticated app users only" on courier_expected_collections for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on bank_accounts;
create policy "authenticated app users only" on bank_accounts for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on courier_payments;
create policy "authenticated app users only" on courier_payments for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on bank_transactions;
create policy "authenticated app users only" on bank_transactions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on cash_transactions;
create policy "authenticated app users only" on cash_transactions for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on cash_settings;
create policy "authenticated app users only" on cash_settings for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on shopify_settings;
create policy "authenticated app users only" on shopify_settings for all using (is_app_user()) with check (is_app_user());

-- shopify_orders: read-only from the client — only SELECT is granted.
-- The future server-side sync writes with the service-role key, which
-- bypasses RLS entirely, so no INSERT/UPDATE policy is needed for it.
drop policy if exists "app users read only" on shopify_orders;
create policy "app users read only" on shopify_orders for select using (is_app_user());

-- Collections v2: single-module redesign (see migration_013_collections_v2.sql)
-- Protees Business Manager — Collections v2: single-module redesign.
--
-- Replaces the "expected vs received" Accounts Receivable model
-- (courier_expected_collections + courier_payments) with a simpler
-- one-step model: a courier is configured ONCE with how it pays
-- (cash, or bank transfer into a specific account), and every
-- "Add Collection" entry for that courier automatically posts to the
-- right ledger — no per-entry bank/payment-type selection.
--
-- courier_expected_collections and courier_payments are NOT dropped
-- here (in case either already holds real data) — they're simply no
-- longer written to by the app. Safe to drop manually later once
-- confirmed empty.
--
-- Safe to re-run.

-- ---------------------------------------------------------------------------
-- Couriers: payment method is now a one-time configuration, not a
-- per-collection choice.
-- ---------------------------------------------------------------------------
alter table couriers add column if not exists payment_method text not null default 'cash' check (payment_method in ('cash', 'bank_transfer'));
alter table couriers add column if not exists bank_account_id bigint references bank_accounts(id);

alter table couriers drop constraint if exists couriers_bank_required;
alter table couriers add constraint couriers_bank_required check (
  (payment_method = 'bank_transfer' and bank_account_id is not null) or
  (payment_method = 'cash' and bank_account_id is null)
);

-- ---------------------------------------------------------------------------
-- Courier collections — one entry per actual collection. Recording one
-- automatically posts a matching bank_transactions credit (if the
-- courier is configured for bank transfer) or cash_transactions cash_in
-- (if cash) — done atomically by the app in one write.
-- ---------------------------------------------------------------------------
create table if not exists courier_collections (
  id bigint generated by default as identity primary key,
  courier_id bigint not null references couriers(id),
  invoice_number text,
  invoice_date date not null default current_date,
  amount numeric(12,2) not null check (amount > 0),
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_courier_collections_courier on courier_collections(courier_id);

-- ---------------------------------------------------------------------------
-- Cash transfers — moving money from a bank account into Office Cash
-- (e.g. withdrawing collected funds to pay cash expenses). Debits the
-- bank, credits cash, atomically.
-- ---------------------------------------------------------------------------
create table if not exists cash_transfers (
  id bigint generated by default as identity primary key,
  bank_account_id bigint not null references bank_accounts(id),
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_cash_transfers_bank on cash_transfers(bank_account_id);

-- ---------------------------------------------------------------------------
-- Widen ledger reference_type check constraints for the new reference
-- kinds. Old values are kept for backward compatibility with any
-- existing rows.
-- ---------------------------------------------------------------------------
alter table bank_transactions drop constraint if exists bank_transactions_reference_type_check;
alter table bank_transactions add constraint bank_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'cash_withdrawal', 'manual', 'courier_collection', 'cash_transfer'));

alter table cash_transactions drop constraint if exists cash_transactions_reference_type_check;
alter table cash_transactions add constraint cash_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'bank_withdrawal', 'expense', 'other', 'courier_collection', 'cash_transfer'));

-- ---------------------------------------------------------------------------
-- Audit trail + RLS
-- ---------------------------------------------------------------------------
drop trigger if exists audit_courier_collections on courier_collections;
create trigger audit_courier_collections before insert or update or delete on courier_collections for each row execute function stamp_and_log_audit();

drop trigger if exists audit_cash_transfers on cash_transfers;
create trigger audit_cash_transfers before insert or update or delete on cash_transfers for each row execute function stamp_and_log_audit();

alter table courier_collections enable row level security;
alter table cash_transfers enable row level security;

drop policy if exists "authenticated app users only" on courier_collections;
create policy "authenticated app users only" on courier_collections for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on cash_transfers;
create policy "authenticated app users only" on cash_transfers for all using (is_app_user()) with check (is_app_user());

-- Shopify multi-store support (see migration_014_shopify_multi_store.sql)
-- Protees Business Manager — Shopify multi-store support.
--
-- shopify_stores holds ONLY non-secret config (domain, display name,
-- live connection status) — Admin API access tokens are never stored
-- here or anywhere in the database. They live exclusively in
-- server-only Vercel environment variables (SHOPIFY_<STORE_KEY>_TOKEN),
-- read only by the /api/shopify-sync serverless function, which writes
-- to shopify_orders using the Supabase service-role key (bypasses RLS).
-- The client only ever reads shopify_stores for status/labels.
--
-- shopify_orders gains store_key (which store an order came from) plus
-- customer_phone/customer_city, both requested for the collections
-- table.
--
-- Safe to re-run.

create table if not exists shopify_stores (
  id bigint generated by default as identity primary key,
  store_key text not null unique,
  display_name text not null,
  store_domain text,
  is_connected boolean not null default false,
  last_synced_at timestamptz,
  last_sync_error text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);

insert into shopify_stores (store_key, display_name) values
  ('protees', 'Protees'),
  ('little_peanuts', 'Little Peanuts')
on conflict (store_key) do nothing;

alter table shopify_orders add column if not exists store_key text references shopify_stores(store_key);
alter table shopify_orders add column if not exists customer_phone text;
alter table shopify_orders add column if not exists customer_city text;

create index if not exists idx_shopify_orders_store on shopify_orders(store_key);

drop trigger if exists audit_shopify_stores on shopify_stores;
create trigger audit_shopify_stores before insert or update or delete on shopify_stores for each row execute function stamp_and_log_audit();

alter table shopify_stores enable row level security;

drop policy if exists "authenticated app users only" on shopify_stores;
create policy "authenticated app users only" on shopify_stores for all using (is_app_user()) with check (is_app_user());

-- Expense Payment Source (see migration_015_expense_payment_source.sql)
-- Protees Business Manager — Expense Payment Source.
--
-- Tracks whether each expense was paid from Office Cash or Online/Bank.
-- Only 'cash' expenses post a linked cash_transactions cash-out entry
-- (see addExpense/updateExpense in DataContext.tsx) — 'online' expenses
-- are recorded and reportable but never touch the Office Cash balance.
--
-- NOT NULL DEFAULT 'cash' on ADD COLUMN backfills every existing expense
-- as Office Cash automatically — no separate backfill step needed, and
-- existing reports/totals are unaffected since 'cash' was already the
-- only behavior before this column existed.
--
-- Safe to re-run.

alter table expenses add column if not exists payment_source text not null default 'cash' check (payment_source in ('cash', 'online'));

-- Master Data Engine (see migration_016_master_data.sql)
-- Protees Business Manager — Master Data Engine.
--
-- A generic, admin-configurable dropdown system. Every "type" (Creditor
-- Categories, Payment Methods, Colors, Units, ...) is a fixed slot defined
-- here in code — but the VALUES inside each slot are fully dynamic: admin
-- can create/rename/archive them from the Settings screen with no
-- developer/deploy step required. This is the same trade-off every real
-- ERP makes (Odoo, Shopify, etc. have fixed models with dynamic records) —
-- a fully meta-meta system (dynamic types too) would add complexity with
-- no real benefit, since the UI needs a label/grouping per type anyway.
--
-- Safe to re-run.

create table if not exists master_data_types (
  key text primary key,
  label text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists master_data_items (
  id bigint generated by default as identity primary key,
  type_key text not null references master_data_types(key) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz,
  unique (type_key, name)
);
create index if not exists idx_master_data_items_type on master_data_items(type_key);

drop trigger if exists audit_master_data_items on master_data_items;
create trigger audit_master_data_items before insert or update or delete on master_data_items for each row execute function stamp_and_log_audit();

insert into master_data_types (key, label, sort_order) values
  ('creditor_category', 'Creditor Categories', 10),
  ('supplier_category', 'Supplier Categories', 20),
  ('material_category', 'Material Categories', 30),
  ('fabric_type', 'Fabric Types', 40),
  ('fabric_gsm', 'Fabric GSM Types', 50),
  ('color', 'Colors', 60),
  ('unit', 'Units', 70),
  ('payment_method', 'Payment Methods', 80),
  ('vendor_type', 'Vendor Types', 90),
  ('service_type', 'Service Types', 100),
  ('tag', 'Tags', 110),
  ('label', 'Labels', 120),
  ('status', 'Statuses', 130)
on conflict (key) do nothing;

-- Seed data — a starting point, not a limit. Admin can rename, archive, or
-- add unlimited values to any of these from Settings → Master Data.
insert into master_data_items (type_key, name, sort_order) values
  ('creditor_category', 'Fabric Supplier', 10),
  ('creditor_category', 'Trader', 20),
  ('creditor_category', 'Printing Vendor', 30),
  ('creditor_category', 'Machinery Vendor', 40),
  ('creditor_category', 'Service Provider', 50),
  ('creditor_category', 'Local Market Supplier', 60),
  ('creditor_category', 'Import Supplier', 70),
  ('payment_method', 'Cash', 10),
  ('payment_method', 'Bank Transfer', 20),
  ('payment_method', 'Cheque', 30),
  ('unit', 'KG', 10),
  ('unit', 'Meter', 20),
  ('unit', 'Roll', 30),
  ('unit', 'Piece', 40),
  ('unit', 'Bundle', 50),
  ('unit', 'Box', 60),
  ('fabric_type', 'Fleece', 10),
  ('fabric_type', 'Jersey', 20),
  ('fabric_type', 'Interlock', 30),
  ('fabric_type', 'Rib', 40),
  ('color', 'Black', 10),
  ('color', 'White', 20),
  ('color', 'Navy', 30)
on conflict (type_key, name) do nothing;

alter table master_data_types enable row level security;
alter table master_data_items enable row level security;

drop policy if exists "authenticated app users only" on master_data_types;
create policy "authenticated app users only" on master_data_types for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on master_data_items;
create policy "authenticated app users only" on master_data_items for all using (is_app_user()) with check (is_app_user());

-- Creditors & Supplier Ledger (see migration_017_creditors.sql)
-- Protees Business Manager — Creditors & Supplier Ledger.
--
-- A creditor is anyone the business owes money to (a supplier/vendor with
-- an outstanding balance). Category is free text, driven by the
-- 'creditor_category' Master Data type (see migration_016) — the admin
-- can add new categories from Settings without a deploy.
--
-- Outstanding balance is never stored — it's computed the same way as
-- every other ledger in this app (advances, courier collections): opening
-- balance + sum(bills) - sum(payments), derived live in CollectionsContext.
--
-- A bill increases what we owe (a purchase/invoice not yet paid) and never
-- touches cash/bank. A payment reduces what we owe AND posts a matching
-- cash_transactions cash-out (if paid from Office Cash) or bank_transactions
-- debit (if paid from a specific bank account) — mirroring exactly how
-- courier_collections posts to cash/bank, just in the opposite direction
-- (money going out, not coming in).
--
-- Safe to re-run.

create table if not exists creditors (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  contact_person text,
  phone text,
  address text,
  notes text,
  opening_balance numeric(12,2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);

create table if not exists creditor_bills (
  id bigint generated by default as identity primary key,
  creditor_id bigint not null references creditors(id) on delete cascade,
  bill_date date not null default current_date,
  amount numeric(12,2) not null check (amount > 0),
  description text,
  reference_number text,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz
);
create index if not exists idx_creditor_bills_creditor on creditor_bills(creditor_id);

create table if not exists creditor_payments (
  id bigint generated by default as identity primary key,
  creditor_id bigint not null references creditors(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  payment_date date not null default current_date,
  payment_type text not null check (payment_type in ('cash', 'bank_transfer')),
  bank_account_id bigint references bank_accounts(id),
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_by_user_id uuid,
  updated_by_username text,
  updated_at timestamptz,
  constraint creditor_payments_bank_required check (
    (payment_type = 'bank_transfer' and bank_account_id is not null) or
    (payment_type = 'cash' and bank_account_id is null)
  )
);
create index if not exists idx_creditor_payments_creditor on creditor_payments(creditor_id);

-- Allow creditor_payment as a reference_type on the shared cash/bank ledgers
-- (widening the existing constraint, not replacing its earlier additions).
alter table cash_transactions drop constraint if exists cash_transactions_reference_type_check;
alter table cash_transactions add constraint cash_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'bank_withdrawal', 'expense', 'other', 'courier_collection', 'cash_transfer', 'creditor_payment'));

alter table bank_transactions drop constraint if exists bank_transactions_reference_type_check;
alter table bank_transactions add constraint bank_transactions_reference_type_check
  check (reference_type in ('courier_payment', 'cash_withdrawal', 'manual', 'courier_collection', 'cash_transfer', 'creditor_payment'));

drop trigger if exists audit_creditors on creditors;
create trigger audit_creditors before insert or update or delete on creditors for each row execute function stamp_and_log_audit();

drop trigger if exists audit_creditor_bills on creditor_bills;
create trigger audit_creditor_bills before insert or update or delete on creditor_bills for each row execute function stamp_and_log_audit();

drop trigger if exists audit_creditor_payments on creditor_payments;
create trigger audit_creditor_payments before insert or update or delete on creditor_payments for each row execute function stamp_and_log_audit();

alter table creditors enable row level security;
alter table creditor_bills enable row level security;
alter table creditor_payments enable row level security;

drop policy if exists "authenticated app users only" on creditors;
create policy "authenticated app users only" on creditors for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on creditor_bills;
create policy "authenticated app users only" on creditor_bills for all using (is_app_user()) with check (is_app_user());

drop policy if exists "authenticated app users only" on creditor_payments;
create policy "authenticated app users only" on creditor_payments for all using (is_app_user()) with check (is_app_user());

-- Staff Module improvements (see migration_018_staff_module.sql)
-- Protees Business Manager — Staff Module improvements.
--
-- 1. employees.is_active — Active/Inactive status. Default true so every
--    existing employee stays active. This is NOT a delete: an inactive
--    employee keeps every advance, salary payment, and audit log entry —
--    the app filters them out of payroll/roster calculations in code,
--    the row itself is never touched by that filtering.
--
--    Who changed it and when is already captured for free by the
--    existing stamp_and_log_audit trigger on employees (it logs every
--    UPDATE with old/new values, including is_active) — no separate
--    audit mechanism needed.
--
--    Scoped to `employees` only, not `supervisors` — Protees Unit has a
--    single supervisor per unit (a config field, not a roster of staff
--    cards), so "Active/Inactive staff card" doesn't apply there.
--
-- 2. advances.payment_method / salary_payments.payment_method — how the
--    payment was made. Free text (like expense_categories), backed by
--    the 'payment_method' Master Data type from migration_016 so admin
--    can add new methods (Easypaisa, JazzCash, ...) without a deploy.
--    Nullable: existing rows have no recorded method (unknown, not
--    "Cash"), the app requires it going forward on new entries.
--
-- Safe to re-run.

alter table employees add column if not exists is_active boolean not null default true;

alter table advances add column if not exists payment_method text;
alter table salary_payments add column if not exists payment_method text;

insert into master_data_items (type_key, name, sort_order) values
  ('payment_method', 'Online Transfer', 40),
  ('payment_method', 'Easypaisa', 50),
  ('payment_method', 'JazzCash', 60)
on conflict (type_key, name) do nothing;
