-- Items an employee buys on credit (Fresh / B), deducted from salary.
create table if not exists employee_item_purchases (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  item_type text not null check (item_type in ('Fresh', 'B')),
  item_name text not null,
  price numeric(12,2) not null check (price > 0),
  purchase_date date not null default current_date,
  salary_payment_id bigint references salary_payments(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid,
  created_by_username text,
  updated_at timestamptz,
  updated_by_user_id uuid,
  updated_by_username text
);

create index if not exists idx_employee_item_purchases_employee on employee_item_purchases(employee_name);
create index if not exists idx_employee_item_purchases_salary on employee_item_purchases(salary_payment_id);

alter table employee_item_purchases enable row level security;
drop policy if exists "authenticated app users only" on employee_item_purchases;
create policy "authenticated app users only" on employee_item_purchases for all using (is_app_user()) with check (is_app_user());

drop trigger if exists audit_employee_item_purchases on employee_item_purchases;
create trigger audit_employee_item_purchases before insert or update or delete on employee_item_purchases for each row execute function stamp_and_log_audit();

-- Each salary deduction kind is stored on its own so advance_deductions only
-- ever holds real advance repayments.
alter table salary_payments add column if not exists security_deduction numeric(12,2) not null default 0;
alter table salary_payments add column if not exists other_deduction numeric(12,2) not null default 0;
alter table salary_payments add column if not exists other_deduction_reason text;
alter table salary_payments add column if not exists item_deduction numeric(12,2) not null default 0;
